force-app/main/default/objects/Asset/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <formula>Product2.Category__r.Category_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <formula>Product2.Model_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model_Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Shipping_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Date__c</fullName>
    <label>Shipping Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores the lookup value with category hierarchy.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <description>This field is used to store the product category type.</description>
    <label>Category Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Language_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Language Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/Category_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the hierarchy of the product category.</description>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Category Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Category_Code__c</fullName>
    <description>This field is used to store the category code of the product.</description>
    <externalId>true</externalId>
    <label>Category Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category Hierarchy</relationshipLabel>
    <relationshipName>CategoryHierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>This object define the relationship between the Contact and Asset object.</description>
    <label>Customer Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Asset object.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Customer Asset</relationshipLabel>
    <relationshipName>Customer_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Asset</relationshipLabel>
    <relationshipName>Customer_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field lookup the category table to define product category.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <description>This field is used to store the model code of the product.</description>
    <label>Model Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Categories__c.field-meta.xml
<CustomField>
    <fullName>Product_Categories__c</fullName>
    <formula>CASE( Category__r.Category_Hierarchy__r.Category_Level__c,

4, if(Category__r.Category__r.Category__r.Name != null, Category__r.Category__r.Category__r.Name, &quot;&quot;) +

if(Category__r.Category__r.Name != null, &apos; / &apos;+Category__r.Category__r.Name +&apos; / &apos;+Category__r.Name, Category__r.Name),

&quot; &quot;)+CASE( Category__r.Category_Hierarchy__r.Category_Level__c,

3, if(Category__r.Category__r.Name != null, Category__r.Category__r.Name +&apos; / &apos;+Category__r.Name, Category__r.Name),

&quot; &quot;)+CASE( Category__r.Category_Hierarchy__r.Category_Level__c,

2, Category__r.Name,

&quot; &quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Categories</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Top_Category__c.field-meta.xml
<CustomField>
    <fullName>Top_Category__c</fullName>
    <description>This field is used to store the top category code of the product.</description>
    <formula>CASE(Category__r.Category_Hierarchy__r.Category_Level__c,

7, Category__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Code__c,

6, Category__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Code__c,

5, Category__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Code__c,

4, Category__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Code__c,

3, Category__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Code__c,

2, Category__r.Category_Hierarchy__r.Category_Hierarchy__r.Category_Code__c,

1, Category__r.Category_Hierarchy__r.Category_Code__c,

&quot;NULL&quot;)</formula>
    <label>Top Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scope_of_Product__c/Scope_of_Product__c.object-meta.xml
<CustomObject>
    <description>This object used to store the contract&apos;s scope of products</description>
    <label>Scope of Product</label>
    <nameField>
        <label>Scope of Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scope_of_Product__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the asset</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Scope of Product</relationshipLabel>
    <relationshipName>Scope_of_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scope_of_Product__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the service contract</description>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Scope of Product</relationshipLabel>
    <relationshipName>Scope_of_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Language_Code__c</fullName>
    <description>This field is used to language code</description>
    <label>Language Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YG_GridController.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Selvaraj T
* @version 1.0
* @created 05/05/2020
* @description 
* This class is used to write the methods for All Stations, All Products and Product Details Page.
*
* @test class name - YG_GridControllerTest
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  15/06/2020           Selvaraj T              Updated the grid logic for product related pages and added grid new column as Qty
*  06/19/2020			Chitrakishore			Modified code for passing the lang code.  
*  10/22/2020       	Jayaprasath				Removed Shipping_Date__c field from this class
*/
public class YG_GridController {
    
    public static User userInformation =  YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
    //public static User userInformation =  YG_Utility.getLoggedInUserInfo('005p0000003rbfUAAQ');
    
    
    /**
	* This method is used to store the grid data for ALL Products page.
	* params: List<Id> - List of Id is used as filter all products grid data based on model code
	* params: String - Has top category and display grid data based on product top category
	**/ 
    @AuraEnabled
    public static productWrapper getProductDetails(List<Id> prodIdList, String prodCat,
                                                   Integer loadLimit, Integer offset, String btnValue){
        
        system.debug('prodIdList::'+prodIdList);
        system.debug('prodCat::'+prodCat);
        system.debug('btnValue::'+btnValue);
        
        productWrapper prodWrap=new productWrapper();
        List<prodDetails> prodDetList=new List<prodDetails>();
                                                       
        List<Id> productId = new List<Id>(); //List to store the product id
        List<Product2> productList = new List<Product2>(); //List to store the product details
        AggregateResult[] totProdSize = new AggregateResult[]{};
        Map<Id,Integer> prodContractMap = new Map<Id,Integer>();
        List<Id> contractAsstList = new List<Id>();
        String topCatCode = '';
        Date now =  date.today();
        Integer contractSize = 0, contractTotSize = 0;    
                                                  
        
        try{
   
            //For Top category 
            if(prodCat != ''){
                prodCat = prodCat.replace('+', ' ');
                system.debug('prodCat::'+prodCat);
            }
            
            //get logged in user lang code
            String langCode = YG_CommonUtils.getLanguageCode(userInformation.LanguageLocaleKey); 
            
            //Get all asset id for particular customer
            ID contactId = userInformation.Contact.ID;  
            List<Id> assetIds = new List<Id>();
            if(prodIdList.size() > 0 && !prodIdList.isEmpty()){
                List<Customer_Asset__c> asstList = [Select Asset__r.Id From Customer_Asset__c Where  Asset__r.Product2Id IN: prodIdList
                                        and Contact__r.ID =: contactId];
                for(Customer_Asset__c asst: asstList){
                    assetIds.add(asst.Asset__r.Id);
                }
            }else{
                assetIds =  YG_HelperClass.getCustomerAssets(contactId);
            }
            
            //get contract assets
            List<Scope_of_Product__c> sopList = [Select Asset__c, Asset__r.Product2Id, Service_Contract__r.StartDate, Service_Contract__r.EndDate 
                                          From Scope_of_Product__c Where Asset__c IN :assetIds and Asset__c != null];
            system.debug('Contract List::'+sopList.size());
            for(Scope_of_Product__c sop: sopList){
                Date endDate = sop.Service_Contract__r.EndDate;
                if(endDate != null){
                    Integer months = now.monthsBetween(endDate);
                    if(endDate < now || (endDate >= now && months < 6)){
                        contractSize++;
                        if(!prodContractMap.containsKey(sop.Asset__r.Product2Id)){
                            prodContractMap.put(sop.Asset__r.Product2Id,1);
                        }else{
                            Integer i = prodContractMap.get(sop.Asset__r.Product2Id) + 1;
                            prodContractMap.put(sop.Asset__r.Product2Id,i);
                        }
                    }
                    if(!contractAsstList.contains(sop.Asset__c)){
                        contractAsstList.add(sop.Asset__c);
                    }
                }
            }
            system.debug('contractAsstList::'+contractAsstList);
            system.debug('prodContractMap::'+prodContractMap);
                                    
            //Query top category code based on product category
            AggregateResult[] allAssProdId = new AggregateResult[]{};
            if(prodCat != ''){

                topCatCode = [Select Name,Category_Hierarchy__r.Category_Code__c FROM Category__c
                              WHERE Name = :prodCat AND Language_Code__c =: langCode].Category_Hierarchy__r.Category_Code__c;
                
                if(btnValue == 'Contracts'){
                    totProdSize = [Select count(Product2Id), Product2.Model_Code__c from Asset 
                               Where Id in:contractAsstList AND Product2.Category__r.Category_Type__c = 'Product' 
                               And Lang_Code__c=:langCode AND Product2.Top_Category__c = :topCatCode
                               GROUP BY Product2.Model_Code__c];
                }else{
                    totProdSize = [Select count(Product2Id), Product2.Model_Code__c from Asset 
                               Where Id in:assetIds AND Product2.Category__r.Category_Type__c = 'Product' 
                               And Lang_Code__c=:langCode AND Product2.Top_Category__c = :topCatCode
                               GROUP BY Product2.Model_Code__c];
                }
                
                allAssProdId = [Select count(SerialNumber) sn, product2.Id from asset 
                                where Id in:assetIds AND Product2.Top_Category__c = :topCatCode 
                                AND Product2.Category__r.Category_Type__c = 'Product' AND Lang_Code__c=:langCode 
                                Group By product2.Id];
                
            }else{
                
                if(btnValue == 'Contracts'){
                    totProdSize = [Select count(Product2Id), Product2.Model_Code__c from Asset 
                               Where Product2.Category__r.Category_Type__c = 'Product' 
                               AND Id in:contractAsstList And Lang_Code__c=:langCode GROUP BY Product2.Model_Code__c];
                }else{
                    totProdSize = [Select count(Product2Id), Product2.Model_Code__c from Asset 
                               Where Product2.Category__r.Category_Type__c = 'Product' 
                               AND Id in:assetIds And Lang_Code__c=:langCode GROUP BY Product2.Model_Code__c];
                }
                 system.debug('totProdSize::'+totProdSize);
                
                allAssProdId = [Select count(SerialNumber) sn, product2.Id from Asset 
                                where Product2.Category__r.Category_Type__c = 'Product' 
                                AND  Id in:assetIds AND Lang_Code__c=:langCode Group By product2.Id];
            }
            

            //Get the product id from asset object based on customer asset
            AggregateResult[] assetList = new AggregateResult[]{};
            if(btnValue == 'Contracts'){
               assetList = YG_HelperClass.getAggAssetsInfo('Product', topCatCode,langCode,loadLimit,offset, contractAsstList); 
            }else{
               assetList = YG_HelperClass.getAggAssetsInfo('Product', topCatCode,langCode,loadLimit,offset, assetIds); 
            }
            
            for(AggregateResult ar: assetList){
                Id prodId = (Id)ar.get('Id');
                if(!productId.contains(prodId)){
                    productId.add(prodId); 
                }
            }
            
            //Get the model code and product record by passing the product id from asset Object
            if(prodIdList.size() > 0 && !prodIdList.isEmpty()){
                productList = YG_HelperClass.getProductInfo(prodIdList, 'Product',langCode);
            }else{
                productList = YG_HelperClass.getProductInfo(productId, 'Product',langCode);
            } 
            
            //Set Column Name
            List<String> cols = new List<String>{System.Label.YG_Product_Categories,System.Label.YG_ProductName_Model,System.Label.YG_Qty,System.Label.YG_Notification};
            prodWrap.colDet = cols;
            
            //Logic to add the product details in wrapper and display in grid
            for(Product2 prod: productList){
                prodDetails prodDet = new prodDetails();
                List<String> serialNo = new List<String>();
                Integer qty = 0;
                Integer contractExpired = 0;
                Integer contractToBeExpired = 0;
                
                prodDet.products =prod.Product_Categories__c;
                prodDet.modelCode = prod.Model_Code__c;
                prodDet.productNameAndCode = prod.Name +' '+prod.Model_Code__c;
                
                prodDet.notifications = new List<String>();
                
                for(AggregateResult ast: allAssProdId){
                    if(prod.Id == (Id)ast.get('Id')){
                        qty = (Integer)ast.get('sn');
                    }
                }
               
                for(Scope_of_Product__c sop: sopList){
                    Date endDate = sop.Service_Contract__r.EndDate;
                    if(prod.Id == sop.Asset__r.Product2Id && endDate != null){
                        Integer months = now.monthsBetween(endDate);
                        if(endDate < now){
                            contractExpired++;
                            prodDet.notifications.add(contractExpired + ' Contracts expired');
                        }
                        if(endDate >= now && months < 6){
                            contractToBeExpired++;
                            prodDet.notifications.add(contractToBeExpired + ' Contracts expiring soon');
                        }
                    }
                }
                
                prodDet.qty = qty;
                if(prodContractMap.get(prod.Id) != null){
                    contractTotSize = contractTotSize + prodContractMap.get(prod.Id);
                }
                prodDetList.add(prodDet);
            }

            prodWrap.prodDet = prodDetList;
            prodWrap.productSize = totProdSize.size();
            if(prodIdList.size() > 0 && !prodIdList.isEmpty()){
                prodWrap.contractSize = contractTotSize;
            }else{
                 prodWrap.contractSize = contractSize;
            }
            
            
            /*
            if(csvSort != ''){
                List<prodDetails> csvProdDet=new List<prodDetails>();
                for(prodDetails csvData: prodWrap.prodDet){
                    System.debug('csvData::'+csvData);
                    if(csvData.notifications != null){
                        List<String> notificationCheck = csvData.notifications;
                        if(notificationCheck.size() > 0){
                            for(String noticheck: notificationCheck){
                                if(noticheck != null){
                                    if(noticheck.contains(csvSort)){
                                        csvProdDet.add(csvData);
                                    }
                                }
                            }
                        } 
                    }
                }
                system.debug('csvProdDet::'+csvProdDet);
                system.debug('csvProdDet.size()::'+csvProdDet.size());
                prodWrap.prodDet = csvProdDet;
            }*/
        }
        catch(Exception e){
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('AllProductsPage','Community Component Error',e.getStackTraceString(),
                                'Class:YG_GridController; Method: getProductDetails(); Line #:'+e.getLineNumber()+'; Message:'+e.getMessage(),
                                UserInfo.getUserId());
            //throw new AuraHandledException(e.getMessage());
        }
        
        
        system.debug('prodWrap::'+prodWrap);
        return prodWrap;
    } 
    
    
    //This Wrapper class is used to store the grid data for All Products page.
    public class productWrapper{
        @AuraEnabled public List<prodDetails> prodDet = new List<prodDetails>();
        @AuraEnabled public List<String> colDet = new List<String>();
        @AuraEnabled public Integer productSize = 0;
        @AuraEnabled public Integer contractSize = 0;
    }
    
    public class prodDetails{
        @AuraEnabled public string products;
        @AuraEnabled public string modelCode;
        @AuraEnabled public string productNameAndCode;
        @AuraEnabled public integer qty;
        @AuraEnabled public List<string> notifications = new List<String>();
        @AuraEnabled public integer notificationCount = 0;
    }
   
        
}