force-app/main/default/objects/Asset/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <formula>Product2.Model_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model_Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Asset Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>This field is used to store the product name of the station</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for project lookup on Asset Object.</description>
    <inlineHelpText>Select project only for system asset.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Revision_No__c.field-meta.xml
<CustomField>
    <fullName>Revision_No__c</fullName>
    <description>This field is used to store the revision number of the station.</description>
    <label>Revision No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Station_Type__c.field-meta.xml
<CustomField>
    <fullName>Station_Type__c</fullName>
    <description>This field is used to store the station type.</description>
    <label>Station Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/Maintenance_Phase__c.object-meta.xml
<CustomObject>
    <description>This object is used to Maintenance phase details of the product and asset.</description>
    <label>Maintenance Phase</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Maintenance Phase</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Phase__c/fields/Ext_Maintenance_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Ext_Maintenance_End_Date__c</fullName>
    <description>This field is used to store the extended maintenance phase end date.</description>
    <label>Ext Maintenance End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Ext_Maintenance_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Ext_Maintenance_Start_Date__c</fullName>
    <description>This field is used to store the extended maintenance phase start date.</description>
    <label>Ext Maintenance Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Maintenance_Phase1_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Phase1_End_Date__c</fullName>
    <description>This field is used to store the maintenance phase1 end date.</description>
    <label>Maintenance Phase1 End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Maintenance_Phase1_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Phase1_Start_Date__c</fullName>
    <description>This field is used to store the maintenance phase1 start date.</description>
    <label>Maintenance Phase1 Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Maintenance_Phase2_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Phase2_End_Date__c</fullName>
    <description>This field is used to store the maintenance phase2 end date.</description>
    <label>Maintenance Phase2 End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Maintenance_Phase2_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Phase2_Start_Date__c</fullName>
    <description>This field is used to store the maintenance phase2 start date.</description>
    <label>Maintenance Phase2 Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the product details.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Maintenance Phase</relationshipLabel>
    <relationshipName>Maintenance_Phase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the project phase details.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Maintenance Phase</relationshipLabel>
    <relationshipName>Maintenance_Phase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Sales_Phase_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Phase_End_Date__c</fullName>
    <description>This field is used to store the sales phase end date.</description>
    <label>Sales Phase End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Sales_Phase_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Phase_Start_Date__c</fullName>
    <description>This field is used to store the sales phase start date.</description>
    <label>Sales Phase Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Phase__c/fields/Sub_Item__c.field-meta.xml
<CustomField>
    <fullName>Sub_Item__c</fullName>
    <label>Sub-Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the plant details</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field lookup the category table to define product category.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <description>This field is used to store the model code of the product.</description>
    <label>Model Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This Object is used to store the Project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the parent project (integrated systems).</description>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for Plant lookup on Project Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <description>This field is used to store the project code.</description>
    <label>Project Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Revision_No__c.field-meta.xml
<CustomField>
    <fullName>Revision_No__c</fullName>
    <description>This field is used to store the revision number of the system.</description>
    <label>Revision No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YG_Community_Configuration__c/YG_Community_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object is used to store the custom setting for community portal.</description>
    <label>YG Community Configuration</label>
</CustomObject>

force-app/main/default/classes/YG_SoftwareLicensesController.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Selvaraj T
* @version 1.0
* @created 13/10/2020
* @description 
* This class is used to write the methods for Software Licenses page.
*
* @test class name - YG_SoftwareLicensesControllerTest
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  
*
*/


public class YG_SoftwareLicensesController {
    
    public static User userInformation =  YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
    
    /**
	 *This method is used to get the software licenses details under particular plant.
     *
	 **/
    @AuraEnabled
    public static softwareWrapper getSoftwareLicenseDetails(String plantCode, List<String> filterValue,Integer loadLimit, Integer offset){
        
        system.debug('plantCode::'+plantCode);
		system.debug('filterValue::'+filterValue);
		system.debug('loadLimit::'+loadLimit);
		system.debug('offset::'+offset);                                                                     
        
        softwareWrapper softWrap = new softwareWrapper();                                                                
        List<softwareLicenseWrapper> softwareLicenseWrapperList = new List<softwareLicenseWrapper>(); //Wrapper list to store the software licenses
        Id pltId = null; //Store the plant Id
        List<Project__c> projList = new List<Project__c>(); //List to store the project record
        List<Id> productId = new List<Id>(); //List to store the product id
        Map<Id,String> projectIdMap = new Map<Id,String>(); //List to store the project id
        List<Maintenance_Phase__c> mtnPhaseList = new List<Maintenance_Phase__c>(); //List to store the maintenance phase details
        List<Asset> assetList = new List<Asset>(); //List to store the asset details
        List<String> astProductName = new List<String>(); //List to store the product name from asset object
        String noti = 'Software no longer supported';
        
        try{
            
            //Get the language code of the user
            String langCode = YG_CommonUtils.getLanguageCode(userInformation.LanguageLocaleKey);
            system.debug('langCode::'+langCode);
            
            //get centum model code and empty model code
            Map<String, YG_Community_Configuration__c> allValues = YG_Community_Configuration__c.getAll();
            String centumModCode = allValues.get('Centum Products Model Code').Text_1__c;
            String emptyModCode = allValues.get('Display Empty Model Code').Text_1__c;
            List<String> centumModCodeLst = centumModCode.split(',');
            List<String> emptyModCodeLst = emptyModCode.split(','); //display '-' in UI for model code in list
            
            //Get plant id based on the plant code
            if(plantCode != null && plantCode != ''){
            
                Plant__c plant = YG_HelperClass.getPlantID(plantCode,langCode);
                pltId = plant.id;
                system.debug('pltId::'+pltId);
                
                //Get the project asociated to the plant
                projList = [Select Id,Name,Project_Code__c,Revision_No__c from Project__c where Plant__r.Id=:pltId];
                system.debug('projList::'+projList);
                for(Project__c proj: projList){
                    projectIdMap.put(proj.Id,proj.Project_Code__c);
                }
                
                //List to get the total software license count
                softWrap.totalSoftwareCount = [Select Count() FROM Asset WHERE Plant__c = :pltId AND Product2.Category__r.Name = 'Software'];
                
                //Get asset details based on the plant id
                if(filterValue.size()>0 && !filterValue.isEmpty() && filterValue != null){
                    assetList = [SELECT Station_Type__c, Product_Name__c, Product2Id ,Product2.Name,Product2.Model_Code__c,Revision_No__c,Project__c,
                                 Project__r.Name, Project__r.Revision_No__c FROM Asset 
                                 WHERE Plant__c = :pltId AND Product2.Category__r.Name = 'Software' AND Product2.Name IN :filterValue  
                                 ORDER BY Product2.Name];
                }
                else{
                    assetList = [SELECT Station_Type__c, Product_Name__c, Product2Id ,Product2.Name,Product2.Model_Code__c,Revision_No__c,Project__c,
                                 Project__r.Name, Project__r.Revision_No__c FROM Asset 
                                 WHERE Plant__c = :pltId AND Product2.Category__r.Name = 'Software' ORDER BY Product2.Name 
                                 LIMIT :loadLimit OFFSET :offset];
                }
                
                for(Asset ar : assetList){
                    if(!productId.contains(ar.Product2Id)){
                        productId.add(ar.Product2Id);
                    }
                    if(ar.Product_Name__c != null && ar.Product_Name__c != '' && !astProductName.contains(ar.Product_Name__c)){
                        astProductName.add(ar.Product_Name__c);
                    }
                    if((ar.Station_Type__c == null || ar.Station_Type__c == '') && !astProductName.contains(ar.Project__r.Name)){
                        astProductName.add(ar.Project__r.Name);
                    }
                }
                
                system.debug('productId::'+productId.size());
                system.debug('astProductName::'+astProductName);
                
                //get maintenance phase details based on product and project id
                mtnPhaseList = [Select Ext_Maintenance_End_Date__c,Ext_Maintenance_Start_Date__c,Maintenance_Phase1_End_Date__c,
                                Maintenance_Phase1_Start_Date__c,Maintenance_Phase2_End_Date__c,Maintenance_Phase2_Start_Date__c,
                                Sales_Phase_End_Date__c,Sales_Phase_Start_Date__c,Product__c,Product__r.Model_Code__c,Item__c,Sub_Item__c 
                                From Maintenance_Phase__c Where Product__c IN :productId OR Item__c = :astProductName];
                
                system.debug('mtnPhaseList::'+mtnPhaseList);
                
                //Iterate the asset list to construct the wrapper
                for(Asset ar : assetList){
                    softwareLicenseWrapper sftLcnWrap = new softwareLicenseWrapper();
                    List<String> notiList = new List<String>();
                    if(ar.Product2.Model_Code__c != null){
                        if(emptyModCodeLst.contains(ar.Product2.Model_Code__c)){
                            sftLcnWrap.modelCode = '-';   
                        }else{
                            sftLcnWrap.modelCode = ar.Product2.Model_Code__c;    
                        }
                    }
                    //sftLcnWrap.modelCode = (String)ar.get('Model_Code__c');
                    sftLcnWrap.name = ar.Product2.Name;
                    sftLcnWrap.id = ar.Product2Id;
                    if(projectIdMap.get(ar.Project__c) != null){
                        sftLcnWrap.systemId = projectIdMap.get(ar.Project__c);
                    }
                    if(ar.Revision_No__c != null){
                        sftLcnWrap.revisionNo = ar.Revision_No__c;
                    }
                    if(centumModCodeLst.contains(ar.Product2.Model_Code__c) && ar.Project__r.Revision_No__c != null){
                     	sftLcnWrap.revisionNo = ar.Project__r.Revision_No__c;   
                    }
                    for(Maintenance_Phase__c mtnPhase: mtnPhaseList){
                        if(centumModCodeLst.contains(ar.Product2.Model_Code__c)){
                            if(mtnPhase.Item__c == ar.Project__r.Name && mtnPhase.Sub_Item__c == ar.Project__r.Revision_No__c && ar.Project__r.Revision_No__c != ''){
                                system.debug('inside centum');
                                system.debug('inside centum'+ar.Product2.Model_Code__c);
                                YG_SystemsController.productPhase prodPhase = YG_SystemsController.getPhaseDetails(mtnPhase);
                                string phase = prodPhase.prodMtnPhase;
                                string phaseEndingIn = prodPhase.phaseEndingIn;
                                String str = '';
                                if(phaseEndingIn.contains('_')){
                                    str = phaseEndingIn.replace('_','');
                                    str = phase + ' ' + Label.YG_ending_in + ' ' +str;
                                    if(!notiList.contains(str)){
                                        notiList.add(str);
                                    }
                                }
                                if(phaseEndingIn == 'Invalid'){
                                    if(!notiList.contains(noti)){
										notiList.add(noti);                                        
                                    }
                                }
                                
                                /*
                                if( Date.today() > mtnPhase.Ext_Maintenance_End_Date__c){
                                    sftLcnWrap.inquiryReq = true;
                                    if(!notiList.contains(phase)){
                                     	notiList.add(Label.YG_Software_no_longer_supported);   
                                    }
                                } */
                            }
                        }
                        if(ar.Station_Type__c == 'HIS'){
                            if(mtnPhase.Item__c == ar.Product_Name__c && mtnPhase.Sub_Item__c == ar.Revision_No__c && ar.Revision_No__c != ''){
                                YG_SystemsController.productPhase prodPhase = YG_SystemsController.getPhaseDetails(mtnPhase);
                                string phase = prodPhase.prodMtnPhase;
                                string phaseEndingIn = prodPhase.phaseEndingIn;
                                String str = '';
                                if(phaseEndingIn.contains('_') && phaseEndingIn != 'Invalid'){
                                    str = phaseEndingIn.replace('_','');
                                    str = phase + ' ' + Label.YG_ending_in + ' ' +str;
                                    if(!notiList.contains(str)){
                                        notiList.add(str);
                                    }
                                }
                                if(phaseEndingIn == 'Invalid'){
                                    if(!notiList.contains(noti)){
                                        notiList.add(noti);
                                    }
                                }
                                /*if( Date.today() > mtnPhase.Ext_Maintenance_End_Date__c){
                                    sftLcnWrap.inquiryReq = true;
                                    notiList.add(Label.YG_Software_no_longer_supported);
                                }*/
                            }
                        }
                        if(ar.Station_Type__c != 'HIS' && !centumModCodeLst.contains(ar.Product2.Model_Code__c)){
                            if(mtnPhase.Product__c == ar.Product2Id && ar.Revision_No__c == mtnPhase.Sub_Item__c && ar.Revision_No__c != ''){
                                YG_SystemsController.productPhase prodPhase = YG_SystemsController.getPhaseDetails(mtnPhase);
                                string phase = prodPhase.prodMtnPhase;
                                string phaseEndingIn = prodPhase.phaseEndingIn;
                                String str = '';
                                if(phaseEndingIn.contains('_') && phaseEndingIn != 'Invalid'){
                                    str = phaseEndingIn.replace('_','');
                                    str = phase + ' ' + Label.YG_ending_in + ' ' +str;
                                    if(!notiList.contains(str)){
                                        notiList.add(str);
                                    }
                                }
                                if(phaseEndingIn == 'Invalid'){
                                    if(!notiList.contains(noti)){
                                        notiList.add(noti);
                                    }
                                }
                                /*if( Date.today() > mtnPhase.Ext_Maintenance_End_Date__c){
                                    sftLcnWrap.inquiryReq = true;
                                    notiList.add(Label.YG_Software_no_longer_supported);
                                }*/
                            }
                        }
                    }
                    system.debug('sftLcnWrap.name::'+sftLcnWrap.name);
                    system.debug('notiList::'+notiList);
                    sftLcnWrap.notiList = notiList;
                    
                    if(sftLcnWrap != null){
                        softwareLicenseWrapperList.add(sftLcnWrap);
                        softWrap.softWrapList = softwareLicenseWrapperList;
                    }
                }
            }else{
                softWrap.totalSoftwareCount = 0;
                softWrap.softWrapList = new List<softwareLicenseWrapper>();
            }
        	
        }
        catch(Exception e){
            softWrap.totalSoftwareCount = 0;
            softWrap.softWrapList = new List<softwareLicenseWrapper>();
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('SoftwareLicensesPage','Backend Process Error',e.getStackTraceString(),
                                'Class:YG_SoftwareLicensesController; Method: getSoftwareLicenseDetails(); Line #:'+e.getLineNumber()+'; Message:'+e.getMessage(),
                                UserInfo.getUserId());
        }
        
        system.debug('softwareWrapper::'+ softWrap);
        return softWrap;
        
    }
    
    //Wrapper to store the software available under the plant
    public class softwareWrapper{
        @AuraEnabled public Integer totalSoftwareCount = 0;
        @AuraEnabled public List<softwareLicenseWrapper> softWrapList = new List<softwareLicenseWrapper>();
    }
    
    public class softwareLicenseWrapper{
        @AuraEnabled public String name = '';
        @AuraEnabled public String id = '';
        @AuraEnabled public String systemId = '-';
        @AuraEnabled public String modelCode = '-';
        @AuraEnabled public String revisionNo = '-';
        @AuraEnabled public Boolean inquiryReq = false;
        @AuraEnabled public List<String> notiList;
    }

}