force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <formula>Product2.Model_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model_Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/MS_Code__c.field-meta.xml
<CustomField>
    <fullName>MS_Code__c</fullName>
    <description>This field is used to store the M S code.</description>
    <label>MS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Asset Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PlantAccount__c.field-meta.xml
<CustomField>
    <fullName>PlantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the plant.</description>
    <label>PlantAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (PlantAccount)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the document details of product and asset.</description>
    <label>Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>This field is used to store the document category based on the type selected.</description>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruction Manuals</fullName>
            </value>
            <value>
                <fullName>Technical Information</fullName>
            </value>
            <value>
                <fullName>Certificates</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>General Specifications</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>FAQs</fullName>
            </value>
            <value>
                <fullName>Training Modules</fullName>
            </value>
            <value>
                <fullName>Specifications and Functions</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Lifecycle Report</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Technical InformationLink</fullName>
            </value>
            <value>
                <fullName>Brochures</fullName>
                <isActive>false</isActive>
                <label>Brochures</label>
            </value>
            <value>
                <fullName>FAQ</fullName>
                <isActive>false</isActive>
                <label>FAQ</label>
            </value>
            <value>
                <fullName>Installation Guide</fullName>
                <isActive>false</isActive>
                <label>Installation Guide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <description>This field is for storing the document name responded from document API call.</description>
    <label>Document Name</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/File_Extension__c.field-meta.xml
<CustomField>
    <fullName>File_Extension__c</fullName>
    <description>This field is used to store the file extension.</description>
    <label>File Extension</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/File_Size__c.field-meta.xml
<CustomField>
    <fullName>File_Size__c</fullName>
    <description>This field is used to store the file size of the document.</description>
    <label>File Size</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <description>This field stores the document link.</description>
    <label>Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/MS_Code__c.field-meta.xml
<CustomField>
    <fullName>MS_Code__c</fullName>
    <description>This field is to store the MS Code return from document API call.</description>
    <label>MS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field lookup with product table for Model Code.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Document</relationshipLabel>
    <relationshipName>Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a lookup object to asset serial number field.</description>
    <inlineHelpText>Please dont use this field for Build 1(This is for the future reference)</inlineHelpText>
    <label>Serial Number</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Document (Serial Number)</relationshipLabel>
    <relationshipName>Document1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This fields defines the attachments belong to document or resource type.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Resources</fullName>
            </value>
            <value>
                <fullName>SysReport</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the plant details</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This field is for storing the locale.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field lookup the category table to define product category.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <description>This field is used to store the model code of the product.</description>
    <label>Model Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to store the type of product.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YG_DocumentController.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Chitrakishore
* @version 1.0
* @created 12/08/2020
* @description 
* This class is used to write the methods for API related call.
*
* @test class name - YG_DocumentControllerTest
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  04/19/2021           Kavya                   Removed Plant__c Object and replaced with Account Object and modified new account lookup field on Asset Object.
*  												Removed Plant__c(Plant) Lookup field from Asset and newly added PlantAccount__c(Account) Lookup field in Asset Object.
*
*/

public class YG_DocumentController {
    
    
    public static User userInformation =  YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
    
    /**
     * This method is for the document API callout and inserting the response to the Document custom object.
     *  
     **/ 
    
    @AuraEnabled    
    public static void getDocumentAPIDetails(String serialNo, List<String> modelCode, String plantCode, String frm){ 
        
        String languageId = YG_CommonUtils.getLanguageCode(userInformation.LanguageLocaleKey);               
        //mainWrapper mainWrap = new mainWrapper();
        
        System.debug('modelCode :::'+modelCode);
        System.debug('serialNo :::'+serialNo);
        
        Product2 prodObj = null;
        String msCode=null;
        ID contactId = userInformation.Contact.ID;  
        try{
            if(null != serialNo && serialNo.trim().length() >0){
                
            	 Asset assetObj;
                 if('product-history'.equalsIgnoreCase(frm)) {
                 	assetObj=[Select MS_Code__c, Product2.Model_Code__c From Asset 
                                      	Where SerialNumber =: serialNo 
                                        AND Lang_Code__c =: languageId limit 1];
                 } else {
                 /*  Plant__c plantObj = YG_HelperClass.getPlantID(plantCode,languageId);*/
                      Account plantObj = YG_HelperClass.getPlantID(plantCode,languageId);
                   assetObj=[Select MS_Code__c, Product2.Model_Code__c From Asset 
                                      	Where PlantAccount__r.Id=:plantObj.Id 
                                      	AND SerialNumber =: serialNo 
                                        AND Lang_Code__c =: languageId limit 1];
                    
                 }
            	
                
                msCode = assetObj.MS_Code__c;                  
                System.debug('getDocumentAPIDetails msCode ::: '+ msCode);
            }
                    
               	Boolean docExist = YG_HelperClass.getAssetOrProductDetails(modelCode, msCode, languageId);        
                //Asset asset =null;
            	System.debug('docExist ::: '+docExist);
            
            	YG_DocumentAPIHandler.DocumentWrapper documentResult = null;
                YG_DocumentAPIHandler.DocumentWrapper certificateResult = null;
            
            	if(!docExist){  
                    
                    List<Document__c> documentList = new List<Document__c>();
                    List<YG_DocumentAPIHandler.DocumentAPIResponseWrapper> docWrapperList 
                            = new List<YG_DocumentAPIHandler.DocumentAPIResponseWrapper>();
                       System.debug('serialNo**'+serialNo);
                    
                    if(null !=modelCode && modelCode.size()>0){
                        for(String model : modelCode) {
                            
                            documentResult = YG_DocumentAPIHandler.searchDocumentCallout(null , model, languageId);
                            
                             if (null !=documentResult && documentResult.success) { 
                                System.debug('Inside If of documentResult');
                               docWrapperList = documentResult.documentAPIResponseList;
                                System.debug('Inside If of docWrapperList :::'+docWrapperList) ;
                               for(YG_DocumentAPIHandler.DocumentAPIResponseWrapper docWrapper : docWrapperList){
                                    Document__c document = populateDocument(docWrapper, 'docs',serialNo, msCode, languageId);
                                    System.debug('document ::: '+document);
                                    documentList.add(document);
                                }
                            }
                        }
                    }
                 
                    
                    else if(null != serialNo  ){
                      /*  certificateResult = YG_DocumentAPIHandler.searchCertificateCallout(serialNo, languageId);  
                        if(null !=certificateResult && certificateResult.success){
                            System.debug('Inside If of certificateResult');
                            docWrapperList = certificateResult.documentAPIResponseList;
                            System.debug('Inside If of docWrapperList>>> :::'+docWrapperList) ;
                            for(YG_DocumentAPIHandler.DocumentAPIResponseWrapper docWrapper : docWrapperList){
                                Document__c document = populateDocument(docWrapper, 'certs',serialNo, msCode , languageId);
                                System.debug('document ::: '+document);
                                documentList.add(document);
                            }
                    	}
                        System.debug('getDocumentAPIDetails msCode ::: '+ msCode);
                        documentResult = YG_DocumentAPIHandler.searchDocumentCallout(msCode , null ,languageId);
                            
                             if (null !=documentResult && documentResult.success) { 
                                System.debug('Inside If of documentResult');
                               docWrapperList = documentResult.documentAPIResponseList;
                                System.debug('Inside If of docWrapperList :::'+docWrapperList) ;
                               for(YG_DocumentAPIHandler.DocumentAPIResponseWrapper docWrapper : docWrapperList){
                                    Document__c document = populateDocument(docWrapper, 'docs', serialNo, msCode, languageId);
                                    System.debug('document ::: '+document);
                                    documentList.add(document);
                                }
                            }
                      */  
                        
                      List<Document__c> docCerttificationList = getCertificationDocumentList(serialNo,languageId,msCode);
                      documentList = docCerttificationList; 
                    }
                    
                    if(documentList.size() >0){ 
                    	insert documentList;
                    }                 
                
            }
            
        }catch(Exception e){
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('API','Community Component Error',e.getStackTraceString(),
                               'Class:v; Method: getDocumentAPIDetails(); Line #:'
                                +e.getLineNumber()+'; Message:'+e.getMessage(),
                               UserInfo.getUserId());
        }
    
        //return mainWrap;
    }
    
    public static List<Document__c> getCertificationDocumentList(String serialNo,String languageId,String msCode){
        
        YG_DocumentAPIHandler.DocumentWrapper documentResult = null;
        YG_DocumentAPIHandler.DocumentWrapper certificateResult = null;
        List<Document__c> documentList = new List<Document__c>();
        List<YG_DocumentAPIHandler.DocumentAPIResponseWrapper> docWrapperList 
                            = new List<YG_DocumentAPIHandler.DocumentAPIResponseWrapper>();
        
        certificateResult = YG_DocumentAPIHandler.searchCertificateCallout(serialNo, languageId);  
        System.debug('certificateResult ::: '+certificateResult);
        if(null !=certificateResult && certificateResult.success){
            System.debug('Inside If of certificateResult');
            docWrapperList = certificateResult.documentAPIResponseList;
            System.debug('Inside If of docWrapperList>>> :::'+docWrapperList) ;
            for(YG_DocumentAPIHandler.DocumentAPIResponseWrapper docWrapper : docWrapperList){
                Document__c document = populateDocument(docWrapper, 'certs',serialNo, msCode , languageId);
                System.debug('document ::: '+document);
                documentList.add(document);
            }
        }
        System.debug('getDocumentAPIDetails msCode ::: '+ msCode);
        documentResult = YG_DocumentAPIHandler.searchDocumentCallout(msCode , null ,languageId);
        
        if (null !=documentResult && documentResult.success) { 
            System.debug('Inside If of documentResult');
            docWrapperList = documentResult.documentAPIResponseList;
            System.debug('Inside If of docWrapperList :::'+docWrapperList) ;
            for(YG_DocumentAPIHandler.DocumentAPIResponseWrapper docWrapper : docWrapperList){
                Document__c document = populateDocument(docWrapper, 'docs', serialNo, msCode, languageId);
                System.debug('document ::: '+document);
                documentList.add(document);
            }
        }
        
        return documentList;
        
    }
    
    
    
    /**
     * This method is for inserting the responses from the document API callout to the custom object (i.e.Document__c) 
     * 
     **/ 
    private static Document__c populateDocument(YG_DocumentAPIHandler.DocumentAPIResponseWrapper docWrapper,
                                        String type,String serialNo, String msCode, String languageId){
    	Document__c document = new Document__c();
        String docName =  docWrapper.DocName;    
        
        if('certs'.equals(type)){
           	docName = docWrapper.DocumentName;                                     
        }                                    
        if(null != docName && docName.length() > 80){
            document.Name = docName.substring(0,79);
            document.Document_Name__c = docName;
            
        }else{
            document.Name = docName; 
            document.Document_Name__c = docName;
        }
                    
       	document.Lang_Code__c = languageId;
        document.Link__c = 'https://'+docWrapper.DownloadURL;
        document.File_Size__c = docWrapper.FileSize;
        document.File_Extension__c = YG_Constants.FILE_EXTENSION;
        document.Type__c = YG_Constants.FILE_TYPE;
                                            
        System.debug('msCode ::: '+msCode);
        System.debug('serialNo ::: '+serialNo);
                                            
        if(null != msCode && msCode.trim().length() >0){
             System.debug('Inside if ::: msCode ::: '+msCode);
        	document.MS_Code__c = msCode;
        }
        /*if(null != serialNo && serialNo.trim().length() >0){
        	document.Serial_Number__c = serialNo;                                        
       	}*/
        
                                            
        if(null != docWrapper.DocType){
            if(docWrapper.DocType.EqualsIgnoreCase('GS')){
                document.Category__c = YG_Constants.GENERAL_SPECIFICATION;
            }else if(docWrapper.DocType.EqualsIgnoreCase('IM')){
                document.Category__c = YG_Constants.INSTRUCTION_MANUAL;
            }else if(docWrapper.DocType.EqualsIgnoreCase('TI')){
                document.Category__c = YG_Constants.TECHNICAL_INFORMATION;
            }else if(docWrapper.DocType.EqualsIgnoreCase('SD')){
                document.Category__c = YG_Constants.DRAWING;
            }
            //document.MS_Code__c = docWrapper.MSCode;
            Product2 prodObj = YG_HelperClass.getProductDetails(docWrapper.Model,docWrapper.LanguageID);
            if(null != prodObj){
                document.Product__c = prodObj.Id;
            } 
       	} else if('certs'.equals(type)){
        	document.Category__c = YG_Constants.CERTIFICATE;    
            
            List<Asset> assetList = YG_HelperClass.getAssetBySerialNumber(docWrapper.SerialNo, languageId);
            if(assetList.size() > 0) {
                document.Serial_Number__c = assetList.get(0).id; 
            }
            
        }
        return document;
    }

}