force-app/main/default/objects/Account/fields/City_Local__c.field-meta.xml
<CustomField>
    <fullName>City_Local__c</fullName>
    <label>City[Local]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Term__c.field-meta.xml
<CustomField>
    <fullName>Credit_Term__c</fullName>
    <description>Number of Days</description>
    <label>Credit Term</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>It has been created for SAP Account Registration Form.</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Office Email</description>
    <inlineHelpText>Office Email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <description>It has been created for common registration form PDF Template.</description>
    <label>Incoterms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>Industry_Code__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Integration_YGSSAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_YGSSAP_Id__c</fullName>
    <description>Unique Id in external system</description>
    <externalId>true</externalId>
    <label>GBPM Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <description>Primary payment mode of the company</description>
    <inlineHelpText>Primary payment mode of the company</inlineHelpText>
    <label>Payment Mode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <description>It has been created for the SAP Account Registration Form.</description>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <description>It has been created for SAP Account Registration Form</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>This is used to store the short name of the account</description>
    <label>Short Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Short_Name_Local__c.field-meta.xml
<CustomField>
    <fullName>Short_Name_Local__c</fullName>
    <description>Abbreviation in Local Language</description>
    <label>Short Name (Local)</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Street_Local__c.field-meta.xml
<CustomField>
    <fullName>Street_Local__c</fullName>
    <description>Company Street in Local Language</description>
    <label>Street (Local)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Reg_No__c.field-meta.xml
<CustomField>
    <fullName>Tax_Reg_No__c</fullName>
    <description>It has been created for a common registration form PDF template.</description>
    <label>Tax Reg No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <description>Company&apos;s VAT Number</description>
    <label>VAT Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/YODA_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>YODA_Account_Number__c</fullName>
    <displayFormat>YAC-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>YODA Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Industry_Code__c/Industry_Code__c.object-meta.xml
<CustomObject>
    <description>Object to store the list of industry codes.</description>
    <label>Industry Code</label>
    <nameField>
        <label>Industry Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Code__c/fields/Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Id__c</fullName>
    <description>Used by Integration team</description>
    <externalId>true</externalId>
    <label>Yokogawa Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Industry_Code__c/fields/Integration_YGSSAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_YGSSAP_Id__c</fullName>
    <externalId>true</externalId>
    <label>Integration YGSSAP Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/YG_AccountDetail.cls
public with sharing class YG_AccountDetail {
    public String selectedRequestType{get;set;}
    private final Account account;
    public String selectedCustomerType{get;set;}

    public YG_AccountDetail() {
        selectedRequestType =ApexPages.currentPage().getParameters().get('selectedRequestType');
        selectedCustomerType =ApexPages.currentPage().getParameters().get('selectedCustomerType');
        account = [SELECT Id, Name,YODA_Account_Number__c,NameLocal,Short_Name__c,Short_Name_Local__c,
                    Integration_YGSSAP_Id__c,Region__c,Industry__r.Integration_Id__c,
                    Type,CurrencyIsoCode,Sales_Organization__c,Distribution_Channel__c,Payment_Mode__c,Credit_Term__c,
                    VAT_Number__c,Tax_Reg_No__c,Payment_Terms__c,Incoterms__c,Email__c,Fax,Website,Phone,ShippingCountry,
                    ShippingState,ShippingStreet,Street_Local__c,ShippingCity,City_Local__c,ShippingPostalCode,CreatedBy.Name,
                    LastModifiedBy.Name,CreatedDate,LastModifiedDate,Description,Industry_Code__c FROM Account
                    WHERE Id = :ApexPages.currentPage().getParameters().get('accID')];
    }
    public Account getAccount() {
        return account;
    }

    //testing purpose
}