force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to store the country and its country code</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>This is used to store the short name of the account</description>
    <label>Short Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the plant details</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for account lookup on plant.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant</relationshipLabel>
    <relationshipName>Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Fax_number__c.field-meta.xml
<CustomField>
    <fullName>Fax_number__c</fullName>
    <label>Fax number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This field is for storing the locale.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>This field is used to store the plant code.</description>
    <label>Plant Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <description>This field is use to store the plant name from API callout</description>
    <label>Plant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Telephone_number__c.field-meta.xml
<CustomField>
    <fullName>Telephone_number__c</fullName>
    <label>Telephone number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/YG_OverviewPlantDetails.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Jayaprasath
* @version 1.0
* @created 09/11/2020
* @description 
* This class is used to write the methods for Overview page Site section.
*
* @test class name - 
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  
*/

public class YG_OverviewPlantDetails {
    
     public static User userInformation =  YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
     //public static User userInformation =  YG_Utility.getLoggedInUserInfo('005p0000003rbfUAAQ');
     
    //This method is used to get the site overview section in Overview page 
    @AuraEnabled
    public static OverviewPlantWrapper getOverviewPlantDetails(String plantCode){
        
        System.debug('plantCode::'+plantCode);
        
        String langCode = YG_CommonUtils.getLanguageCode(userInformation.LanguageLocaleKey); 
        OverviewPlantWrapper overviewPlantWap=new OverviewPlantWrapper();
        
        
        try{
            
            Id accId = userInformation.Contact.AccountId;
            
             //To get the plant id
            Plant__c plant =  [SELECT ID,Name,Plant_Name__c,Plant_Code__c,Lang_Code__c,//Country__c,
                               Fax_number__c,Location__c,Telephone_number__c,Account__r.Name, Account__r.Short_Name__c 
                               FROM Plant__c WHERE Plant_Code__c =: plantCode AND Account__c =: accId AND Lang_Code__c =:langCode];
            
                 
                    overviewPlantWap.name = plant.Plant_Name__c;
                    overviewPlantWap.accname = plant.Account__r.Name;
                    overviewPlantWap.sitenumber = plant.Plant_Code__c;
                   
                    if(plant.Account__r.Short_Name__c == null){
                        overviewPlantWap.shortname = '-'; 
                    }
                    else{
                        overviewPlantWap.shortname = plant.Account__r.Short_Name__c;
                    }
                    /*if(plant.Country__c == null){
                        overviewPlantWap.country = '-';  
                    }
                    else{
                        overviewPlantWap.country = plant.Country__c;
                    }*/
                    if(plant.Location__c == null){
                        overviewPlantWap.location = '-';   
                    }
                    else{
                        overviewPlantWap.location = plant.Location__c;
                    }
                    if(plant.Telephone_number__c == null){
                        overviewPlantWap.phone = '-';    
                    }
                    else{
                        overviewPlantWap.phone = plant.Telephone_number__c;
                    }
                    if(plant.Fax_number__c == null){
                        overviewPlantWap.fax = '-';     
                    }
                    else{
                        overviewPlantWap.fax = plant.Fax_number__c; 
                    }
            
                
                 system.debug('Plant List ::'+overviewPlantWap);
                

            
            }
        
        catch(Exception e){
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('Overview page Site section','Community Component Error',e.getStackTraceString(),
                                'Class:YG_OverviewPlantDetails; Method: getOverviewPlantDetails(); Line #:'+e.getLineNumber()+'; Message:'+e.getMessage(),
                                UserInfo.getUserId());
        }
        return overviewPlantWap;
        }
    
     public class OverviewPlantWrapper{
        @AuraEnabled public String name;
        @AuraEnabled public String sitenumber;
        @AuraEnabled public String accname;
        @AuraEnabled public String shortname;
        @AuraEnabled public String country;
        @AuraEnabled public String location;
        @AuraEnabled public String phone;
        @AuraEnabled public String fax;
    }

}