force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>This field is used to store the DUNS number.</description>
    <label>DUNS Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Asset Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PlantAccount__c.field-meta.xml
<CustomField>
    <fullName>PlantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the plant.</description>
    <label>PlantAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (PlantAccount)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Plant)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <label>Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/Customer_Plant__c.object-meta.xml
<CustomObject>
    <description>This is a Junction object for Contact and Plant</description>
    <label>Customer Plant</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Customer Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Plant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for contact lookup on Customer Plant Object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Plant</relationshipLabel>
    <relationshipName>Customer_Plant</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Customer Plant Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Customer Plant</relationshipLabel>
    <relationshipName>Customer_Plant</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
                <default>true</default>
                <label>Request site access</label>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the plant details</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for account lookup on plant.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant</relationshipLabel>
    <relationshipName>Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This field is for storing the locale.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>This field is used to store the plant code.</description>
    <label>Plant Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <description>This is field is used to store the contract number</description>
    <label>Contract No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/YG_Community_Configuration__c/YG_Community_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object is used to store the custom setting for community portal.</description>
    <label>YG Community Configuration</label>
</CustomObject>

force-app/main/default/classes/YG_ContractAPIHandlerTest.cls
/********************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Vinod A
* @version 1.0
* @created 22/07/2020
* @description 
* This test class for YG_ContractAPIHandler apex class.
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  04/21/2021 			Kavya 					Removed Plant__c Object and replaced with Account Object also removed Customer_Plant__c Object and replaced with AccountContactRelation Object.
*												Removed Plant__c(Plant) Lookup field from Asset and newly added PlantAccount__c(Account) Lookup field in Asset Object.
*
*/

@isTest
public class YG_ContractAPIHandlerTest {
    
    @testSetup static void testDataSetup() {
        
    }
    
    @isTest static void contractTestMethod() {
        
        //Inserting test account record
        Account acc = new account();
        acc.name='XYZ Account';   
        acc.AccountNumber = '200086397';
          acc.Type = 'Customer';
        //acc.DUNS_Number__c=102224533; 
        insert acc; 
        
        //Inserting test contact record
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        insert con;
        
        //Inserting test plant record
        /*List<Plant__c> plantList=new List<Plant__c>();
        Plant__c plant1=new Plant__c();
        plant1.Name = 'TestPlant';
        plant1.Account__c = acc.Id;  
        plant1.Plant_Code__c = '300000123';
        plant1.Lang_Code__c = 'EN';
        plantList.add(plant1);
        insert plant1;*/
        
        //Inserting test plant record
        List<Account> plantList=new List<Account>();
        Account plant1=new Account();
        plant1.Name = 'TestPlant';
        plant1.ParentId = acc.Id;  
        plant1.AccountNumber = '300000123';
        plant1.Type = 'Plant';
        plantList.add(plant1);
        insert plant1;
        
        List<String> pltList=new List<String>();
        /*for(Plant__c plt: plantList){
            pltList.add(plt.Plant_Code__c);
        }*/
        for(Account plt: plantList){
            pltList.add(plt.AccountNumber);
        }
        
        //Inserting test customer plant record
       /* List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
        Customer_Plant__c cusPlant1=new Customer_Plant__c();
        cusPlant1.Contact__c = con.Id;
        cusPlant1.Plant__c = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;*/
        
        //Inserting test customer plant record
        List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
        AccountContactRelation cusPlant1=new AccountContactRelation();
        cusPlant1.ContactId = con.Id;
        cusPlant1.AccountId = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;
        
        Asset ass=new Asset();
        ass.Name = '0A74B68F-D39C-11E9-94D1-0AE1E5432EEC';
        ass.AccountId = acc.Id;
        ass.PlantAccount__c = plant1.Id;
        insert ass;
        
        ServiceContract servCont=new ServiceContract();
        servCont.Name = '라이온코리아(인천) N(세제)(통합) Plant LION Co. Korea (Incheon)';
        servCont.Contract_No__c = 'YKO-L00078-2001-01';
        servCont.AccountId = acc.Id;
        servCont.StartDate = date.today()-30;
        servCont.EndDate = date.today()+90;
        Insert servCont;
        
        //Insert custom setting records
        List<YG_Community_Configuration__c> configList = new List<YG_Community_Configuration__c>();
        YG_Community_Configuration__c contractApi = new YG_Community_Configuration__c();
        contractApi.Name = 'ContractAPIEndpointUrl';
        contractApi.Text_1__c = 'https://library.yokogawa.com:8180/contract/search';
        configList.add(contractApi);
        
        YG_Community_Configuration__c contractItemApi = new YG_Community_Configuration__c();
        contractItemApi.Name = 'ContractItemAPIEndpointUrl';
        contractItemApi.Text_1__c = 'https://library.yokogawa.com:8180/contractitem/search';
        configList.add(contractItemApi);
        
        YG_Community_Configuration__c contProdApi = new YG_Community_Configuration__c();
        contProdApi.Name = 'ContractProductAPIEndpointUrl';
        contProdApi.Text_1__c = 'https://library.yokogawa.com:8180/contractproduct/search';
        configList.add(contProdApi);
        
        YG_Community_Configuration__c contMainteApi = new YG_Community_Configuration__c();
        contMainteApi.Name = 'ContractMainteCrmAPIEndpointUrl';
        contMainteApi.Text_1__c = 'https://library.yokogawa.com:8180/contractmaintecrm/search';
        configList.add(contMainteApi);
        
        YG_Community_Configuration__c inspectApi = new YG_Community_Configuration__c();
        inspectApi.Name = 'ContractInspectionAPIEndpointUrl';
        inspectApi.Text_1__c = 'https://library.yokogawa.com:8180/inspect/search';
        configList.add(inspectApi);
        
        YG_Community_Configuration__c systemid=new YG_Community_Configuration__c();
        systemid.Name = 'ShippingAPISystemId';
        systemid.Text_1__c = 'F5cJnZkn';
        configList.add(systemid);
        
        YG_Community_Configuration__c contSync=new YG_Community_Configuration__c();
        contSync.Name = 'Contract API Sync Duration in Days';
        contSync.Text_1__c = '1';
        configList.add(contSync);
        
        YG_Community_Configuration__c selfReg=new YG_Community_Configuration__c();
        selfReg.Name = 'YGSelfRegisterAccountId';
        selfReg.Text_1__c = '001p000000tzRDXAA2';
        configList.add(selfReg);
        
        insert configList;
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        insert user;
        System.RunAs(user){
            
            Test.startTest();
            
            Boolean resValue = YG_ContractAPIHandler.checkContractSync();
            Map<String, Id> contractMap = new Map<String, Id>();
            //System.debug('contractMap::::'+contractMap);
            
            List<YG_ContractAPIHandler.ContractAPI> responseList=new List<YG_ContractAPIHandler.ContractAPI>();
            //Calling mock response
            Test.setMock(HttpCalloutMock.class, new YG_ContractAPIHandlerMockCallout());
            contractMap = YG_ContractAPIHandler.getContractAPI();
            System.debug('contractMap::'+contractMap);
            Id contId = contractMap.get('YKO-L00078-2001-01');
            Map<String, Id> inputContProd=new Map<String, Id>();
            String contNo = servCont.Contract_No__c;
            Id contractId = servCont.Id;
            inputContProd.put(contNo,contractId);
            System.debug('inputContProd::'+inputContProd);
            System.debug('pltList::'+pltList);
            
            //For the Negative test case
            Boolean result = YG_ContractAPIHandler.getContractProduct();
            System.debug('result::'+result);
            Map<String, Map<String, Id>> servMenuMap=new Map<String, Map<String, Id>>();
            servMenuMap = YG_ContractAPIHandler.getContractServMenu('YEA-L00316-1806-01');
            
            Test.stopTest();
        }
        
    }
    
    @isTest static void contractTestMethod2() {
        
        //Inserting test account record
        Account acc = new account();
        acc.name='XYZ Account';   
        acc.AccountNumber = '200086397';
         acc.Type = 'Customer';
        //acc.DUNS_Number__c=102224533; 
        insert acc; 
        
        //Inserting test contact record
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        insert con;
        
        //Inserting test plant record
       /* List<Plant__c> plantList=new List<Plant__c>();
        Plant__c plant1=new Plant__c();
        plant1.Name = 'TestPlant';
        plant1.Account__c = acc.Id;  
        plant1.Plant_Code__c = '300000123';
        plant1.Lang_Code__c = 'EN';
        plantList.add(plant1);
        insert plant1;*/
        
        //Inserting test plant record
       List<Account> plantList=new List<Account>();
        Account plant1=new Account();
        plant1.Name = 'TestPlant';
        plant1.ParentId = acc.Id;  
        plant1.AccountNumber = '300000123';
        plant1.Type = 'Plant';
        plantList.add(plant1);
        insert plant1;
        
        List<String> pltList=new List<String>();
        /*for(Plant__c plt: plantList){
            pltList.add(plt.Plant_Code__c);
        }*/
        for(Account plt: plantList){
            pltList.add(plt.AccountNumber);
        }
        
        //Inserting test customer plant record
        /*List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
        Customer_Plant__c cusPlant1=new Customer_Plant__c();
        cusPlant1.Contact__c = con.Id;
        cusPlant1.Plant__c = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;*/
        
        //Inserting test customer plant record
        List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
        AccountContactRelation cusPlant1=new AccountContactRelation();
        cusPlant1.ContactId = con.Id;
        cusPlant1.AccountId = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;
        
        Asset ass=new Asset();
        ass.Name = '0A74B68F-D39C-11E9-94D1-0AE1E5432EEC';
        ass.AccountId = acc.Id;
        ass.PlantAccount__c = plant1.Id;
        insert ass;
        
        ServiceContract servCont=new ServiceContract();
        servCont.Name = '라이온코리아(인천) N(세제)(통합) Plant LION Co. Korea (Incheon)';
        servCont.Contract_No__c = 'YKO-L00078-2001-01';
        servCont.AccountId = acc.Id;
        servCont.StartDate = date.today()-30;
        servCont.EndDate = date.today()+90;
        Insert servCont;
        
        //Insert custom setting records
        List<YG_Community_Configuration__c> configList = new List<YG_Community_Configuration__c>();
        YG_Community_Configuration__c contractApi = new YG_Community_Configuration__c();
        contractApi.Name = 'ContractAPIEndpointUrl';
        contractApi.Text_1__c = 'https://library.yokogawa.com:8180/contract/search';
        configList.add(contractApi);
        
        YG_Community_Configuration__c contractItemApi = new YG_Community_Configuration__c();
        contractItemApi.Name = 'ContractItemAPIEndpointUrl';
        contractItemApi.Text_1__c = 'https://library.yokogawa.com:8180/contractitem/search';
        configList.add(contractItemApi);
        
        YG_Community_Configuration__c contProdApi = new YG_Community_Configuration__c();
        contProdApi.Name = 'ContractProductAPIEndpointUrl';
        contProdApi.Text_1__c = 'https://library.yokogawa.com:8180/contractproduct/search';
        configList.add(contProdApi);
        
        YG_Community_Configuration__c contMainteApi = new YG_Community_Configuration__c();
        contMainteApi.Name = 'ContractMainteCrmAPIEndpointUrl';
        contMainteApi.Text_1__c = 'https://library.yokogawa.com:8180/contractmaintecrm/search';
        configList.add(contMainteApi);
        
        YG_Community_Configuration__c inspectApi = new YG_Community_Configuration__c();
        inspectApi.Name = 'ContractInspectionAPIEndpointUrl';
        inspectApi.Text_1__c = 'https://library.yokogawa.com:8180/inspect/search';
        configList.add(inspectApi);
        
        YG_Community_Configuration__c systemid=new YG_Community_Configuration__c();
        systemid.Name = 'ShippingAPISystemId';
        systemid.Text_1__c = 'F5cJnZkn';
        configList.add(systemid);
        
        YG_Community_Configuration__c contSync=new YG_Community_Configuration__c();
        contSync.Name = 'Contract API Sync Duration in Days';
        contSync.Text_1__c = '1';
        configList.add(contSync);
        
        YG_Community_Configuration__c selfReg=new YG_Community_Configuration__c();
        selfReg.Name = 'YGSelfRegisterAccountId';
        selfReg.Text_1__c = '001p000000tzRDXAA2';
        configList.add(selfReg);
        
        insert configList;
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        insert user;
        System.RunAs(user){
            
            Test.startTest();
            //Calling mock response
            Test.setMock(HttpCalloutMock.class, new YG_ContractAPIHandlerMockCallout());
            Boolean result = YG_ContractAPIHandler.getContractProduct();
            System.assertEquals(true, result);
            Map<String, Map<String, Id>> servMenuMap=new Map<String, Map<String, Id>>();

            
            Test.stopTest();
        }
        
    }
    
    @isTest static void contractTestMethod3() {
        //Inserting test account record
        Account acc = new account();
        acc.name='XYZ Account';   
        acc.AccountNumber = '200086397';
        acc.Type = 'Customer';
        //acc.DUNS_Number__c=102224533; 
        insert acc; 
        
        //Inserting test contact record
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        insert con;
        
        //Inserting test plant record
       /* List<Plant__c> plantList=new List<Plant__c>();
        Plant__c plant1=new Plant__c();
        plant1.Name = 'TestPlant';
        plant1.Account__c = acc.Id;  
        plant1.Plant_Code__c = '300000123';
        plant1.Lang_Code__c = 'EN';
        plantList.add(plant1);
        insert plant1;*/
        
        //Inserting test plant record
       List<Account> plantList=new List<Account>();
        Account plant1=new Account();
        plant1.Name = 'TestPlant';
        plant1.ParentId = acc.Id;  
        plant1.AccountNumber = '300000123';
        plant1.Type = 'Plant';
        plantList.add(plant1);
        insert plant1;
        
        List<String> pltList=new List<String>();
        /*for(Plant__c plt: plantList){
            pltList.add(plt.Plant_Code__c);
        }*/
        for(Account plt: plantList){
            pltList.add(plt.AccountNumber);
        }
        
        //Inserting test customer plant record
       /* List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
        Customer_Plant__c cusPlant1=new Customer_Plant__c();
        cusPlant1.Contact__c = con.Id;
        cusPlant1.Plant__c = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;*/
        
        //Inserting test customer plant record
        List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
        AccountContactRelation cusPlant1=new AccountContactRelation();
        cusPlant1.ContactId = con.Id;
        cusPlant1.AccountId = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;
        
        Asset ass=new Asset();
        ass.Name = '0A74B68F-D39C-11E9-94D1-0AE1E5432EEC';
        ass.AccountId = acc.Id;
        ass.PlantAccount__c = plant1.Id;
        insert ass;
        
        ServiceContract servCont=new ServiceContract();
        servCont.Name = '라이온코리아(인천) N(세제)(통합) Plant LION Co. Korea (Incheon)';
        servCont.Contract_No__c = 'YKO-L00078-2001-01';
        servCont.AccountId = acc.Id;
        servCont.StartDate = date.today()-30;
        servCont.EndDate = date.today()+90;
        Insert servCont;
        
        //Insert custom setting records
        List<YG_Community_Configuration__c> configList = new List<YG_Community_Configuration__c>();
        
        YG_Community_Configuration__c contMainteApi = new YG_Community_Configuration__c();
        contMainteApi.Name = 'ContractMainteCrmAPIEndpointUrl';
        contMainteApi.Text_1__c = 'https://library.yokogawa.com:8180/contractmaintecrm/search';
        configList.add(contMainteApi);
        
        YG_Community_Configuration__c inspectApi = new YG_Community_Configuration__c();
        inspectApi.Name = 'ContractInspectionAPIEndpointUrl';
        inspectApi.Text_1__c = 'https://library.yokogawa.com:8180/inspect/search';
        configList.add(inspectApi);
        
        YG_Community_Configuration__c systemid=new YG_Community_Configuration__c();
        systemid.Name = 'ShippingAPISystemId';
        systemid.Text_1__c = 'F5cJnZkn';
        configList.add(systemid);
        
        insert configList;
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        insert user;
        System.RunAs(user){
            
            Test.startTest();
            //Calling mock response
            Test.setMock(HttpCalloutMock.class, new YG_ContractAPIHandlerMockCallout());
            Map<String, Map<String, Id>> servMenuMap=new Map<String, Map<String, Id>>();
            servMenuMap = YG_ContractAPIHandler.getContractServMenu('YEA-L00316-1806-01');
            Map<String, Id> entitleResMap = new Map<String, Id>();
            String lcaNo = null;
            boolean resultVal = false;
            for(String lca: servMenuMap.keySet()){
                lcaNo = lca;
                entitleResMap =  servMenuMap.get(lca);
            }
            System.assertEquals('YEA-L00316-1806-01', lcaNo);
            //Negative test case
            Boolean res = YG_ContractAPIHandler.getInspectionDetails(servMenuMap);
            System.debug('res::'+res);
            //resultMap::{YEA-L00316-1806-01={155C7BDB-9F03-42E5-B0F9-AD018B696759=550p00000009E7fAAE, A41A473C-0667-40D0-8645-50B2F42FEA0F=550p00000009E7gAAE, C80F05AB-9A6A-401A-811A-D12950CA3DEC=550p00000009E7hAAE}}
            Test.stopTest();
        }
    }
    
    @isTest static void contractTestMethod4() {
        //Inserting test account record
        Account acc = new account();
        acc.name='XYZ Account';   
        acc.AccountNumber = '200086397';
        acc.Type = 'Customer';
        //acc.DUNS_Number__c=102224533; 
        insert acc; 
        
        //Inserting test contact record
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        insert con;
        
        //Inserting test plant record
       /* List<Plant__c> plantList=new List<Plant__c>();
        Plant__c plant1=new Plant__c();
        plant1.Name = 'TestPlant';
        plant1.Account__c = acc.Id;  
        plant1.Plant_Code__c = '300000123';
        plant1.Lang_Code__c = 'EN';
        plantList.add(plant1);
        insert plant1;*/
        
        //Inserting test plant record
        List<Account> plantList=new List<Account>();
        Account plant1=new Account();
        plant1.Name = 'TestPlant';
        plant1.ParentId = acc.Id;  
        plant1.AccountNumber = '300000123';
         plant1.Type = 'Plant';
        plantList.add(plant1);
        insert plant1;
        
        List<String> pltList=new List<String>();
       /* for(Plant__c plt: plantList){
            pltList.add(plt.Plant_Code__c);
        }*/
        for(Account plt: plantList){
            pltList.add(plt.AccountNumber);
        }
        
        //Inserting test customer plant record
        /*List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
        Customer_Plant__c cusPlant1=new Customer_Plant__c();
        cusPlant1.Contact__c = con.Id;
        cusPlant1.Plant__c = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;*/
        
         //Inserting test customer plant record
        List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
        AccountContactRelation cusPlant1=new AccountContactRelation();
        cusPlant1.ContactId = con.Id;
        cusPlant1.AccountId = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;
        
        Asset ass=new Asset();
        ass.Name = '0A74B68F-D39C-11E9-94D1-0AE1E5432EEC';
        ass.AccountId = acc.Id;
        ass.PlantAccount__c = plant1.Id;
        insert ass;
        
        ServiceContract servCont=new ServiceContract();
        servCont.Name = '라이온코리아(인천) N(세제)(통합) Plant LION Co. Korea (Incheon)';
        servCont.Contract_No__c = 'YKO-L00078-2001-01';
        servCont.AccountId = acc.Id;
        servCont.StartDate = date.today()-30;
        servCont.EndDate = date.today()+90;
        Insert servCont;
        
        //Insert custom setting records
        List<YG_Community_Configuration__c> configList = new List<YG_Community_Configuration__c>();
        
        YG_Community_Configuration__c inspectApi = new YG_Community_Configuration__c();
        inspectApi.Name = 'ContractInspectionAPIEndpointUrl';
        inspectApi.Text_1__c = 'https://library.yokogawa.com:8180/inspect/search';
        configList.add(inspectApi);
        
        YG_Community_Configuration__c systemid=new YG_Community_Configuration__c();
        systemid.Name = 'ShippingAPISystemId';
        systemid.Text_1__c = 'F5cJnZkn';
        configList.add(systemid);
        
        insert configList;
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        insert user;
        System.RunAs(user){
            
            Test.startTest();
            //Calling mock response
            Test.setMock(HttpCalloutMock.class, new YG_ContractAPIHandlerMockCallout());
            Map<String, Map<String, Id>> inspectMap=new Map<String, Map<String, Id>>();
            String lca = 'YEA-L00316-1806-01';
            Map<String, Id> mapValues=new Map<String, Id>();
            mapValues.put('155C7BDB-9F03-42E5-B0F9-AD018B696759', '550p00000009E7fAAE');
            mapValues.put('A41A473C-0667-40D0-8645-50B2F42FEA0F', '550p00000009E7gAAE');
            mapValues.put('C80F05AB-9A6A-401A-811A-D12950CA3DEC', '550p00000009E7hAAE');
            Boolean res = YG_ContractAPIHandler.getInspectionDetails(inspectMap);
            System.assertEquals(true, res);
            Test.stopTest();
        }
    }
    
     @isTest static void contractTestMethod5() {
        //Inserting test account record
        Account acc = new account();
        acc.name='XYZ Account';   
        acc.AccountNumber = '200086397';
        acc.Type = 'Customer';
        //acc.DUNS_Number__c=102224533; 
        insert acc; 
        
        //Inserting test contact record
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        insert con;
        
        /*//Inserting test plant record
        List<Plant__c> plantList=new List<Plant__c>();
        Plant__c plant1=new Plant__c();
        plant1.Name = 'TestPlant';
        plant1.Account__c = acc.Id;  
        plant1.Plant_Code__c = '300000123';
        plant1.Lang_Code__c = 'EN';
        plantList.add(plant1);
        insert plant1;*/
        
         //Inserting test plant record
        List<Account> plantList=new List<Account>();
        Account plant1=new Account();
        plant1.Name = 'TestPlant';
        plant1.ParentId = acc.Id;  
        plant1.AccountNumber = '300000123';
         plant1.Type = 'Plant';
        plantList.add(plant1);
        insert plant1;
         
        List<String> pltList=new List<String>();
       /* for(Plant__c plt: plantList){
            pltList.add(plt.Plant_Code__c);
        }*/
         for(Account plt: plantList){
            pltList.add(plt.AccountNumber);
        }
        
       /* //Inserting test customer plant record
        List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
        Customer_Plant__c cusPlant1=new Customer_Plant__c();
        cusPlant1.Contact__c = con.Id;
        cusPlant1.Plant__c = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;*/
         
         //Inserting test customer plant record
        List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
        AccountContactRelation cusPlant1=new AccountContactRelation();
        cusPlant1.ContactId = con.Id;
        cusPlant1.AccountId = plant1.Id;
        cusPlant1.Status__c = 'Approved site access';
        cusPlantList.add(cusPlant1);
        insert cusPlant1;
        
        Asset ass=new Asset();
        ass.Name = '0A74B68F-D39C-11E9-94D1-0AE1E5432EEC';
        ass.AccountId = acc.Id;
        ass.PlantAccount__c = plant1.Id;
        insert ass;
        
        ServiceContract servCont=new ServiceContract();
        servCont.Name = '라이온코리아(인천) N(세제)(통합) Plant LION Co. Korea (Incheon)';
        servCont.Contract_No__c = 'YKO-L00078-2001-01';
        servCont.AccountId = acc.Id;
        servCont.StartDate = date.today()-30;
        servCont.EndDate = date.today()+90;
        Insert servCont;
        
        //Insert custom setting records
        List<YG_Community_Configuration__c> configList = new List<YG_Community_Configuration__c>();
        YG_Community_Configuration__c contractApi = new YG_Community_Configuration__c();
        contractApi.Name = 'ContractAPIEndpointUrl';
        contractApi.Text_1__c = 'https://library.yokogawa.com:8180/contract/search';
        configList.add(contractApi);
        
        YG_Community_Configuration__c contractItemApi = new YG_Community_Configuration__c();
        contractItemApi.Name = 'ContractItemAPIEndpointUrl';
        contractItemApi.Text_1__c = 'https://library.yokogawa.com:8180/contractitem/search';
        configList.add(contractItemApi);
        
        YG_Community_Configuration__c contProdApi = new YG_Community_Configuration__c();
        contProdApi.Name = 'ContractProductAPIEndpointUrl';
        contProdApi.Text_1__c = 'https://library.yokogawa.com:8180/contractproduct/search';
        configList.add(contProdApi);
        
        YG_Community_Configuration__c contMainteApi = new YG_Community_Configuration__c();
        contMainteApi.Name = 'ContractMainteCrmAPIEndpointUrl';
        contMainteApi.Text_1__c = 'https://library.yokogawa.com:8180/contractmaintecrm/search';
        configList.add(contMainteApi);
        
        YG_Community_Configuration__c inspectApi = new YG_Community_Configuration__c();
        inspectApi.Name = 'ContractInspectionAPIEndpointUrl';
        inspectApi.Text_1__c = 'https://library.yokogawa.com:8180/inspect/search';
        configList.add(inspectApi);
        
        YG_Community_Configuration__c systemid=new YG_Community_Configuration__c();
        systemid.Name = 'ShippingAPISystemId';
        systemid.Text_1__c = 'F5cJnZkn';
        configList.add(systemid);
        
        YG_Community_Configuration__c contSync=new YG_Community_Configuration__c();
        contSync.Name = 'Contract API Sync Duration in Days';
        contSync.Text_1__c = '1';
        configList.add(contSync);
        
        YG_Community_Configuration__c selfReg=new YG_Community_Configuration__c();
        selfReg.Name = 'YGSelfRegisterAccountId';
        selfReg.Text_1__c = '001p000000tzRDXAA2';
        configList.add(selfReg);
        
        insert configList;
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        insert user;
        System.RunAs(user){
            
            Test.startTest();
            //Without Calling mock response
            Map<String, Id> contractMap = new Map<String, Id>();
             contractMap = YG_ContractAPIHandler.getContractAPI();
            System.assertEquals(0, contractMap.size());
            Test.stopTest();
        }
    }
    
}