force-app/main/default/objects/Account/fields/Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Language_Code__c</fullName>
    <label>Language Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <formula>Product2.Category__r.Category_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <formula>Product2.Model_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model_Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/MS_Code__c.field-meta.xml
<CustomField>
    <fullName>MS_Code__c</fullName>
    <description>This field is used to store the M S code.</description>
    <label>MS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PlantAccount__c.field-meta.xml
<CustomField>
    <fullName>PlantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the plant.</description>
    <label>PlantAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (PlantAccount)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for project lookup on Asset Object.</description>
    <inlineHelpText>Select project only for system asset.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>This field is used to store the progress details of case.</description>
    <label>Progress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServAir_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>ServAir_Created_Date__c</fullName>
    <label>ServAir Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores the lookup value with category hierarchy.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <description>This field is used to store the product category type.</description>
    <label>Category Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Language_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Language Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/Category_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the hierarchy of the product category.</description>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Category Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category Hierarchy</relationshipLabel>
    <relationshipName>CategoryHierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_User_Roles__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Roles__c</fullName>
    <description>This field is used to store the Portal User Roles</description>
    <label>Portal User Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
                <label>Customer Admin</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Super Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>This object define the relationship between the Contact and Asset object.</description>
    <label>Customer Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Asset object.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Customer Asset</relationshipLabel>
    <relationshipName>Customer_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Asset</relationshipLabel>
    <relationshipName>Customer_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Entitlement_type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_type__c</fullName>
    <description>This field is used to store the entitlement type of service contract</description>
    <label>Entitlement type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field lookup the category table to define product category.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <description>This field is used to store the model code of the product.</description>
    <label>Model Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This Object is used to store the Project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for account lookup on Project Object.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PlantAccount__c.field-meta.xml
<CustomField>
    <fullName>PlantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the plant</description>
    <label>PlantAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project (PlantAccount)</relationshipLabel>
    <relationshipName>Project2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_categories__c.field-meta.xml
<CustomField>
    <fullName>Contract_categories__c</fullName>
    <label>Contract categories</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial Automation</fullName>
            </value>
            <value>
                <fullName>Test &amp; Measurement</fullName>
            </value>
            <value>
                <fullName>Life Innovation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <description>This is field is used to store the contract number</description>
    <label>Contract No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>LCA</fullName>
            </value>
            <value>
                <fullName>Annual support (hardware)</fullName>
            </value>
            <value>
                <fullName>Annual support (software)</fullName>
            </value>
            <value>
                <fullName>Annual support (hardware&amp;software)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/YG_Sales_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>YG_Sales_Manager_Name__c</fullName>
    <description>This field is used to store the sales manager Name</description>
    <label>YG Sales Manager Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/YG_TestDataFactory.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Pravakar
* @version 1.0
* @created 20/07/2021
* @description 
* This is a data factory class.
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  
*/
public with sharing class YG_TestDataFactory {
    public static List<Account> createAccounts(Integer numAccts, String type, String parentAccId) {
        List<Account> lstAccounts = new List<Account>();
        for(Integer i=0;i<numAccts;i++) {
            Account objAcc = new Account(Name='TestAccount' + i, Type = type);
            if(parentAccId!=null && parentAccId!='') objAcc.ParentId = parentAccId;
            lstAccounts.add(objAcc);
        }
        return lstAccounts;
    }
    public static List<Contact> createContacts(Integer numCons, String accId, String portalUserRole, Boolean isActive) {
        List<Contact> lstContact = new List<Contact>();
        for(Integer i=0;i<numCons;i++) {
            Contact objCon = new Contact(LastName='TestConLast' + i, FirstName='TestConLast' + i, Email='TestConEmail'+ i+'@test.com', Portal_User_Roles__c=portalUserRole, Status__c=isActive);
            if(accId !=null && accId != '') objCon.accountid = accId;
            lstContact.add(objCon);
        }
        return lstContact;
    }
    public static List<AccountContactRelation> createAccountContactRelations (Integer nums, Id accId, Id conId) {
        List<AccountContactRelation> lstAccConRel = new List<AccountContactRelation>();
        for(Integer i=0;i<nums;i++) {
            AccountContactRelation objAccConRel = new AccountContactRelation(AccountId=accId, ContactId=conId);
            lstAccConRel.add(objAccConRel);
        }
        return lstAccConRel;
    }
    public static List<Category_Hierarchy__c> createCategoryHierarchies (Integer nums){
        List<Category_Hierarchy__c> lstCatHier=new List<Category_Hierarchy__c>();
        for(Integer i=0;i<nums;i++) {
            Category_Hierarchy__c objCatHier = new Category_Hierarchy__c(Name = 'Test Hirarchy'+i);
            lstCatHier.add(objCatHier);
        }
        return lstCatHier;
    }
    public static List<Category__c> createCategories (Integer nums, Id catHireId){
        List<Category__c> lstCategory=new List<Category__c>();
        for(Integer i=0;i<nums;i++) {
            Category__c objCategory = new Category__c(Name = 'Test Category'+i);
            if(catHireId!=null && catHireId!='') objCategory.Category_Hierarchy__c = catHireId;
            lstCategory.add(objCategory);
        }
        return lstCategory;
    }
    public static List<Product2> createProducts (Integer nums){
        List<Product2> lstProduct=new List<Product2>();
        for(Integer i=0;i<nums;i++) {
            Product2 objProduct = new Product2(Name = 'Test Category'+i);
            lstProduct.add(objProduct);
        }
        return lstProduct;
    }
    public static List<Asset> createAssets (Integer nums, Id ProdId, Id AccId, Id ConId){
        List<Asset> lstAsset=new List<Asset>();
        for(Integer i=0;i<nums;i++) {
            Asset objAsset = new Asset(Name = 'Test Asset'+i, Product2Id=ProdId, AccountId=AccId, ContactId=ConId);
            lstAsset.add(objAsset);
        }
        return lstAsset;
    }
    public static List<Customer_Asset__c> createCustomerAssets (Integer nums, Id assetId, Id ContractId){
        List<Customer_Asset__c> lstCustomAsset=new List<Customer_Asset__c>();
        for(Integer i=0;i<nums;i++) {
            Customer_Asset__c objCustomAsset = new Customer_Asset__c(Asset__c=assetId, Contact__c=ContractId);
            lstCustomAsset.add(objCustomAsset);
        }
        return lstCustomAsset;
    }
    public static List<ServiceContract> createServiceContracts (Integer nums, Id accId){
        List<ServiceContract> lstServContract=new List<ServiceContract>();
        for(Integer i=0;i<nums;i++) {
            ServiceContract objServContract = new ServiceContract(Name='Test Service'+i, AccountId=accId);
            lstServContract.add(objServContract);
        }
        return lstServContract;
    }
    public static List<Entitlement> createEntitlements (Integer nums, Id accId){
        List<Entitlement> lstEntitlement=new List<Entitlement>();
        for(Integer i=0;i<nums;i++) {
            Entitlement objEntitlement = new Entitlement(Name='Test Entitlement'+i, AccountId=accId);
            lstEntitlement.add(objEntitlement);
        }
        return lstEntitlement;
    }
    public static List<Case> createCases (Integer nums, Id accId,Id conId, String typ, String stat, String reas, String prog, Date createdDate){
        List<Case> lstCase=new List<Case>();
        for(Integer i=0;i<nums;i++) {
            Case objCase = new Case(AccountId=accId, ContactId=conId, Type=typ, Status=stat, Reason=reas, Progress__c=prog, ServAir_Created_Date__c = createdDate);
            lstCase.add(objCase);
        }
        return lstCase;
    }
    public static List<User> createUsers (Integer nums, Id profId){
        List<User> lstUser=new List<User>();
        for(Integer i=0;i<nums;i++) {
            User objUser = new User(FirstName='Test First'+i, LastName='Test Last'+i, ProfileID=profId, Alias='Test Alias'+i, isActive=true, Email='testEmail'+i+'@test.com');
            lstUser.add(objUser);
        }
        return lstUser;
    }
    public static User createUser (String firstName, String lastName, String alias, String email, String userName, Boolean isActive, Id profId, Id ConId, String langLocKey){
        User objUser = new User();
        objUser.FirstName = firstName;
        objUser.LastName = lastName;
        objUser.Email = email;
        objUser.Alias = alias;
        objUser.IsActive = isActive;
        objUser.profileId = profId;
        objUser.Username = userName;
        objUser.ContactId = ConId;
        objUser.LanguageLocaleKey=langLocKey;
        return objUser;
    }  
    public static Case createCase (Id accID, Id conId, Id prodId, String type, String reason, String status){
        Case objCase = new Case();
        objCase.AccountId = accID;
        objCase.ContactId = conId;
        objCase.productId = prodId;
        objCase.Type = type;
        objCase.Reason = reason;
        objCase.Status = status;
        return objCase;
    }  
    public static Product2 createProduct (String name,String modelCode, String langCode, Id catId){
        Product2 objProduct = new Product2();
        objProduct.Name = name;
        objProduct.Model_Code__c = modelCode;
        objProduct.Lang_Code__c = langCode;
        objProduct.Category__c = catId;
        return objProduct;
    }  
    public static Entitlement createEntitlement (String name,String type, Id accId, Id serviceId, Id assetId){
        Entitlement objEntitlement = new Entitlement();
        objEntitlement.Name = name;
        objEntitlement.Entitlement_type__c = type;
        objEntitlement.AccountId = accId;
        objEntitlement.ServiceContractId = serviceId; 
        objEntitlement.AssetId = assetId; 
        return objEntitlement;
    } 
    public static ServiceContract createServiceContract (String name,String conType, Id accId, String conNumber, String salesMangName, String contCategory, Date startDate, Date endDate){
        ServiceContract objServCon = new ServiceContract();
        objServCon.Name = name;
        objServCon.AccountId = accId;
        objServCon.Contract_No__c = conNumber;
        objServCon.Contract_Type__c = conType;            
        objServCon.YG_Sales_Manager_Name__c = salesMangName;
        objServCon.Contract_categories__c = contCategory;
        objServCon.StartDate = startDate;
        objServCon.EndDate = endDate;
        return objServCon;
    } 
    public static Asset createAsset (String name,String slNo, Id accId, String msCode, String status, String langCode, Id prodId, Id conId, Id plantAccId){
        Asset objAsset=new Asset();
        objAsset.Name = name;
        objAsset.Product2Id = prodId;
        objAsset.AccountId = accId;
        objAsset.ContactId = conId;
        objAsset.SerialNumber = slNo;
      //  objAsset.PlantAccount__c = plantAccId;
       // objAsset.Project__c = projectId;
        objAsset.MS_Code__c = msCode;
        objAsset.Status = status;
        objAsset.Lang_Code__c=langCode;
        return objAsset;
    }  
    public static Category__c createCategory (String name, String catType, String langCode, Id catHierId){
        Category__c objCategory = new Category__c();
        objCategory.Name=name;
        objCategory.Category_Hierarchy__c = catHierId;
        objCategory.Category_Type__c = catType;
        objCategory.Language_Code__c = langCode;
        return objCategory;
    }
    public static Category_Hierarchy__c createCategoryHire (String catCode, Integer catLevel, Integer disSeq, Id catHireId, String upperCatCode){
        Category_Hierarchy__c objCatHire = new Category_Hierarchy__c();
        objCatHire.Category_Code__c= catCode;
        objCatHire.Category_Level__c = catLevel;
        objCatHire.Display_Sequence__c = disSeq;
        objCatHire.Category_Hierarchy__c = catHireId;
        objCatHire.Upper_Category_Code__c=upperCatCode;
        return objCatHire;
    }
    public static Project__c createProject (Id accId, String pojCode){
        Project__c objProj=new Project__c();
        objProj.Account__c = accId;
        objProj.Project_Code__c = pojCode;
        return objProj;
    }
    public static WorkOrder createWorkOrder (string status, string WOrderOrigin){
        WorkOrder WO= new WorkOrder();
        WO.Status=status;
        WO.Work_Order_Origin__c=WOrderOrigin;
        return WO;
    }
}