force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>This field is used to store the company name of the self register contact</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_User_Roles__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Roles__c</fullName>
    <description>This field is used to store the Portal User Roles</description>
    <label>Portal User Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
                <label>Customer Admin</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Super Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/YG_Community_Configuration__c/YG_Community_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object is used to store the custom setting for community portal.</description>
    <label>YG Community Configuration</label>
</CustomObject>

force-app/main/default/classes/YG_LoggedUserRoleControllerTest.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Jayaprasath
* @version 1.0
* @created 09/30/2020
* @description 
* This test class for YG_LoggedUserRoleController apex class.
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  
*/

@istest
public class YG_LoggedUserRoleControllerTest {
    
     @istest static void getOverviewGridTestMethod(){
        //Insert test account record
        Account acc = new account();
        acc.name='ABC Test Account';
        insert acc;    
        
        //Insert test contact record
        List<Contact> cCount = new List<Contact>();
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id;
        con.Portal_User_Roles__c='CA';
        con.phone = '7845123256';
        con.Company_Name__c = 'testVerticurl';
        con.Status__c = true;
        cCount.add(con);
         
         //Insert test contact record
        Contact con1 = new Contact();   
        con1.FirstName='User1';
        con1.LastName='CVX';
        con1.Email='cvxauuser0211@chevron.com';
        con1.accountid=acc.id;
        con1.Portal_User_Roles__c='CU';
        con1.phone = '8745123256';
        con1.Company_Name__c = 'testYOK'; 
        con1.Status__c = true;
        cCount.add(con1);
         
         Contact c=new Contact();
         c.LastName = 'JP';
         c.Portal_User_Roles__c = 'CU';
         c.AccountId = acc.id;
         c.Status__c = true;
         c.Company_Name__c = 'test';
         cCount.add(c);
         insert cCount;
        
     
        //Inserting test portal user record
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        insert user;
        
         
        YG_Community_Configuration__c selfRegAcc = new YG_Community_Configuration__c(name= 'YGSelfRegisterAccountId',Text_1__c=acc.id);
        insert selfRegAcc;
         
          System.RunAs(user){
              test.startTest();
                //Line to cover getNotifyUserRole() method 
              
              YG_LoggedUserRoleController.NoftifyUserRoleWapper obj = new YG_LoggedUserRoleController.NoftifyUserRoleWapper();
              try {
                  obj=YG_LoggedUserRoleController.getNotifyUserRole();
              } catch(DMLException e) {
                  
              }
              
              test.stopTest();
           
          }
         
    }

}