force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Asset Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PlantAccount__c.field-meta.xml
<CustomField>
    <fullName>PlantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the plant.</description>
    <label>PlantAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (PlantAccount)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for project lookup on Asset Object.</description>
    <inlineHelpText>Select project only for system asset.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores the lookup value with category hierarchy.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Level__c.field-meta.xml
<CustomField>
    <fullName>Category_Level__c</fullName>
    <formula>TEXT(Category_Hierarchy__r.Category_Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/Category_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the hierarchy of the product category.</description>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Category Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Category_Code__c</fullName>
    <description>This field is used to store the category code of the product.</description>
    <externalId>true</externalId>
    <label>Category Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category Hierarchy</relationshipLabel>
    <relationshipName>CategoryHierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Level__c.field-meta.xml
<CustomField>
    <fullName>Category_Level__c</fullName>
    <description>This field is used to store the category level of the product.</description>
    <label>Category Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/fields/Display_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Display_Sequence__c</fullName>
    <description>This field is used to store the display sequence of the product category.</description>
    <label>Display Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>This object define the relationship between the Contact and Asset object.</description>
    <label>Customer Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Asset</relationshipLabel>
    <relationshipName>Customer_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/Customer_Plant__c.object-meta.xml
<CustomObject>
    <description>This is a Junction object for Contact and Plant</description>
    <label>Customer Plant</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Customer Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Plant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for contact lookup on Customer Plant Object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Plant</relationshipLabel>
    <relationshipName>Customer_Plant</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Customer Plant Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Customer Plant</relationshipLabel>
    <relationshipName>Customer_Plant</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
                <default>true</default>
                <label>Request site access</label>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the plant details</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for account lookup on plant.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant</relationshipLabel>
    <relationshipName>Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This field is for storing the locale.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>This field is used to store the plant code.</description>
    <label>Plant Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lang_Code__c.field-meta.xml
<CustomField>
    <fullName>Lang_Code__c</fullName>
    <defaultValue>&quot;EN&quot;</defaultValue>
    <description>This is used to store the language code of a record to differentiate the translations based on logged in user.</description>
    <label>Lang Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This Object is used to store the Project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for account lookup on Project Object.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for Plant lookup on Project Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PlantAccount__c.field-meta.xml
<CustomField>
    <fullName>PlantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the plant</description>
    <label>PlantAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project (PlantAccount)</relationshipLabel>
    <relationshipName>Project2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <description>This field is used to store the project code.</description>
    <label>Project Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/YG_CommonControllerTest.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Chitrakishore
* @version 1.0
* @created 25/06/2020
* @description 
* This test class for YG_CommonController apex class.
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  04/21/2021 			Kavya 					Removed Plant__c Object and replaced with Account Object also removed Customer_Plant__c Object and replaced with AccountContactRelation Object.

.*												Removed Plant__c(Plant) Lookup field from Asset and Project Objects and newly added PlantAccount__c(Account) Lookup field in Asset  and Project Object.
*  
*
*/

@isTest
public class YG_CommonControllerTest {
    
    @isTest static void commonTestMethod(){
        Test.startTest();
        
        //Insert test account record
        Account acc = new account();
        acc.name='XYZ Account'; 
        acc.AccountNumber = null; 
        acc.Type = 'Customer';
        insert acc;

		//Insert test contact record        
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        con.Status__c = true;
        insert con;
        
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        
        //Insert test customer portal user record   
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        
        insert user;
        System.debug('userId'+user.Id);
        
         
        //Insert test plant record   
            /*List<Plant__c> plantList=new List<Plant__c>();
            Plant__c plant1=new Plant__c();
            plant1.Name = 'TestPlant';
            plant1.Account__c = acc.Id;  
            plant1.Plant_Code__c = '300000142';
        	plant1.Lang_Code__c = 'EN';
            plantList.add(plant1);
            insert plantList;*/
        
        //Insert test plant record   
            List<Account> plantList=new List<Account>();
            Account plant1=new Account();
            plant1.Name = 'TestPlant';
            plant1.ParentId = acc.Id;  
            plant1.AccountNumber = '300000142';
         	plant1.Type = 'Plant';
            plantList.add(plant1);
            insert plantList;
            
            //Insert test customer plant record   
            /*List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
            Customer_Plant__c cusPlant1=new Customer_Plant__c();
            cusPlant1.Contact__c = con.Id;
            cusPlant1.Plant__c = plant1.Id;
        	cusPlant1.Status__c = 'Approved site access';
            cusPlantList.add(cusPlant1);
            insert cusPlantList;*/
        
         //Insert test customer plant record   
        List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
            AccountContactRelation cusPlant1=new AccountContactRelation();
            cusPlant1.ContactId = con.Id;
            cusPlant1.AccountId = plant1.Id;
        	cusPlant1.Status__c = 'Approved site access';
            cusPlantList.add(cusPlant1);
            insert cusPlantList;
        
        	//Insert test project record   
            List<Project__c> projectList=new List<Project__c>();
            Project__c proj1=new Project__c();
            proj1.Account__c = acc.Id;
            proj1.PlantAccount__c = plant1.Id;
            proj1.Project_Code__c = 'VP700250';
            projectList.add(proj1);
            insert projectList;
        
        	List<Category_Hierarchy__c> catHierList=new List<Category_Hierarchy__c>();
            Category_Hierarchy__c catHier1=new Category_Hierarchy__c(Category_Code__c = '10000000', Category_Level__c = 1, Display_Sequence__c = 500,
                                                                     Category_Hierarchy__c = NULL);
            catHierList.add(catHier1);
            insert catHierList;
            
            List<Category__c> catList=new List<Category__c>();
            Category__c catg1 = new Category__c(Name = 'Distributed Control Systems (DCS)', Category_Hierarchy__c = catHier1.Id,
                                              Category_Type__c = 'System', Language_Code__c = 'EN');
            
            catList.add(catg1);
            insert catList;
            
            
            List<Product2> prodList=new List<Product2>();
            Product2 prod1=new Product2();
            prod1.Name = 'Node Expansion Package (for AFV10)';
            prod1.Model_Code__c = 'LFS1550';
            prod1.Product_Type__c = 'Hardware';
            prod1.Category__c = catg1.Id;
            //prod1.Production_Date__c = Date.newInstance(2014, 12, 17);
            prodList.add(prod1);
            
            Insert prodList;
            
            List<Asset> assList=new List<Asset>();
            Asset ass1=new Asset();
            ass1.Name = 'FCS0111';
            ass1.Product2Id = prod1.Id;
           ass1.AccountId = acc.Id;
            ass1.ContactId = con.Id;
            ass1.SerialNumber = 'FCS0111';
            ass1.PlantAccount__c = plant1.Id;
            ass1.Project__c = proj1.Id;
            ass1.MS_Code__c = 'FCS0111';
            ass1.Status = 'Installed';
            ass1.Lang_Code__c='EN';
            assList.add(ass1);
        	insert assList;
        
        	List<Customer_Asset__c> custAsstList =new List<Customer_Asset__c>();
        	Customer_Asset__c custAsst = new Customer_Asset__c();
        	custAsst.Contact__C = con.id;	
            custAsst.Asset__c = ass1.id;
        	custAsstList.add(custAsst);
        	insert custAsstList;
        
        YG_Community_Configuration__c selfReg = new YG_Community_Configuration__c(name= 'YGSelfRegisterAccountId',Text_1__c='001p000000tzRDX');
        insert selfReg;
        Id selfRegId = selfReg.Text_1__c;
        
        //execute method as portal user   
        System.RunAs(user){
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('loggedInUser Id: ' + UserInfo.getUserId());
            System.debug('Current Profile: ' + UserInfo.getProfileId());
            
            User loggedInUser= YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
           
            
            String langCode;
            
            try{                
                YG_CommonController.CommonWrapper commWrapper = YG_CommonController.getPlantInfo(langCode);                
                
                YG_CommonController.checkContractOrIndividualCustomer();
                
                YG_CommonController.MenuWrapper commmenuWrapper = YG_CommonController.getMenuInfo();
                
            }
            catch (Exception e) {
                System.debug('Error in testclass for YG_CommonControllerTest.commonTestMethod() ::: '+e.getMessage());
            }
        }
        
        Test.stopTest();
    }
    
    @isTest static void commonTestMethodUser1(){
        Test.startTest();
        
        //Insert test account record
        Account acc = new account();
        acc.name='XYZ Account'; 
        acc.AccountNumber = '963258'; 
        acc.Type = 'Customer';
        insert acc;

		//Insert test contact record        
        Contact con = new Contact();   
        con.FirstName='User';
        con.LastName='CVX AU';
        con.Email='cvxauuser011@chevron.com';
        con.accountid=acc.id; 
        con.Status__c = true;
        insert con;
        
        
        Profile profile = [Select Id From Profile Where Name='Customer Portal User'];
        
        //Insert test customer portal user record   
        User user = new User(Alias = 'comm', Email='yg.qa167@gmail.com',ContactId=con.id,
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = profile.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='yg.qa167@gmail.com');
        
        insert user;
        System.debug('userId'+user.Id);
        
         
        //Insert test plant record   
           /* List<Plant__c> plantList=new List<Plant__c>();
            Plant__c plant1=new Plant__c();
            plant1.Name = 'TestPlant';
            plant1.Account__c = acc.Id;  
            plant1.Plant_Code__c = '300000142';
        	plant1.Lang_Code__c = 'EN';
            plantList.add(plant1);
            insert plantList;*/
        //Insert test plant record   
        List<Account> plantList=new List<Account>();
            Account plant1=new Account();
            plant1.Name = 'TestPlant';
            plant1.ParentId = acc.Id;  
            plant1.AccountNumber = '300000142';
        	plant1.Type = 'Plant';
            plantList.add(plant1);
            insert plantList;
            
            //Insert test customer plant record   
            /*List<Customer_Plant__c> cusPlantList=new List<Customer_Plant__c>();
            Customer_Plant__c cusPlant1=new Customer_Plant__c();
            cusPlant1.Contact__c = con.Id;
            cusPlant1.Plant__c = plant1.Id;
        	cusPlant1.Status__c = 'Approved site access';
            cusPlantList.add(cusPlant1);
            insert cusPlantList;*/
        
        //Insert test customer plant record   
            List<AccountContactRelation> cusPlantList=new List<AccountContactRelation>();
            AccountContactRelation cusPlant1=new AccountContactRelation();
            cusPlant1.ContactId = con.Id;
            cusPlant1.AccountId = plant1.Id;
        	cusPlant1.Status__c = 'Approved site access';
            cusPlantList.add(cusPlant1);
            insert cusPlantList;
        
        	//Insert test project record   
            List<Project__c> projectList=new List<Project__c>();
            Project__c proj1=new Project__c();
            proj1.Account__c = acc.Id;
            proj1.PlantAccount__c = plant1.Id;
            proj1.Project_Code__c = 'VP700250';
            projectList.add(proj1);
            insert projectList;
        
        	List<Category_Hierarchy__c> catHierList=new List<Category_Hierarchy__c>();
            Category_Hierarchy__c catHier1=new Category_Hierarchy__c(Category_Code__c = '10000000', Category_Level__c = 1, Display_Sequence__c = 500,
                                                                     Category_Hierarchy__c = NULL);
            catHierList.add(catHier1);
            insert catHierList;
            
            List<Category__c> catList=new List<Category__c>();
            Category__c catg1 = new Category__c(Name = 'Distributed Control Systems (DCS)', Category_Hierarchy__c = catHier1.Id,
                                              Category_Type__c = 'System', Language_Code__c = 'EN');
            
            catList.add(catg1);
            insert catList;
            
            
            List<Product2> prodList=new List<Product2>();
            Product2 prod1=new Product2();
            prod1.Name = 'Node Expansion Package (for AFV10)';
            prod1.Model_Code__c = 'LFS1550';
            prod1.Product_Type__c = 'Hardware';
            prod1.Category__c = catg1.Id;
           // prod1.Production_Date__c = Date.newInstance(2014, 12, 17);
            prodList.add(prod1);
            
            Insert prodList;
            
            List<Asset> assList=new List<Asset>();
            Asset ass1=new Asset();
            ass1.Name = 'FCS0111';
            ass1.Product2Id = prod1.Id;
            ass1.AccountId = acc.Id;
            ass1.ContactId = con.Id;
            ass1.SerialNumber = 'FCS0111';
           ass1.PlantAccount__c = plant1.Id;
            ass1.Project__c = proj1.Id;
            ass1.MS_Code__c = 'FCS0111';
            ass1.Status = 'Installed';
            ass1.Lang_Code__c='EN';
            assList.add(ass1);
        	insert assList;
        
        	List<Customer_Asset__c> custAsstList =new List<Customer_Asset__c>();
        	Customer_Asset__c custAsst = new Customer_Asset__c();
        	custAsst.Contact__C = con.id;	
            custAsst.Asset__c = ass1.id;
        	custAsstList.add(custAsst);
        	insert custAsstList;
        
        YG_Community_Configuration__c selfReg = new YG_Community_Configuration__c(name= 'YGSelfRegisterAccountId',Text_1__c=acc.id);
        insert selfReg;
        Id selfRegId = selfReg.Text_1__c;
        
        //execute method as portal user   
        System.RunAs(user){
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('loggedInUser Id: ' + UserInfo.getUserId());
            System.debug('Current Profile: ' + UserInfo.getProfileId());
            
            User loggedInUser= YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
           
            
            String langCode;
            
            try{
                YG_CommonController.checkContractOrIndividualCustomer();
                
                YG_CommonController.MenuWrapper commmenuWrapper = YG_CommonController.getMenuInfo();                
            }
            catch (Exception e) {
                System.debug('Error in testclass for YG_CommonControllerTest.commonTestMethod() ::: '+e.getMessage());
            }
        }
        
        Test.stopTest();
    }

}