force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>This field is used to store the company name of the self register contact</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_User_Roles__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Roles__c</fullName>
    <description>This field is used to store the Portal User Roles</description>
    <label>Portal User Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
                <label>Customer Admin</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Super Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/YG_Community_Configuration__c/YG_Community_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object is used to store the custom setting for community portal.</description>
    <label>YG Community Configuration</label>
</CustomObject>

force-app/main/default/classes/YG_LoggedUserRoleController.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Jayaprasath
* @version 1.0
* @created 09/17/2020
* @description 
* This class is used to write the methods for Logged user roles.
*
* @test class name - YG_LoggedUserRoleControllerTest
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  
*/

public class YG_LoggedUserRoleController {
    
    public static User userInformation =  YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
    //public static User userInformation =  YG_Utility.getLoggedInUserInfo('005p0000003rbfUAAQ');
   

     // This method is to display the user details on the popup 
    @AuraEnabled
    public static NoftifyUserRoleWapper getNotifyUserRole(){
        
        NoftifyUserRoleWapper userRoleWap=new NoftifyUserRoleWapper();
        Id conId = userInformation.Contact.Id;
        Id accId = userInformation.Contact.AccountId;
        try{
        	//to get the logged contact info
            Contact con = [Select id, toLabel(Portal_User_Roles__c), FirstName, LastName, Email, Phone, Account.Name,  
                           Company_Name__c from Contact where id = :conId and status__c =: true ];
            userRoleWap.fName = con.FirstName;
            userRoleWap.lName = con.LastName;
            userRoleWap.email = con.Email;
            userRoleWap.phone = con.Phone;            
            userRoleWap.Role = con.Portal_User_Roles__c;
           
            //to identify the self register account 
            Map<String, YG_Community_Configuration__c> allValues = new Map<String, YG_Community_Configuration__c>();        
            allValues = YG_Community_Configuration__c.getAll();
            Id selfRegAccId = allValues.get('YGSelfRegisterAccountId').Text_1__c;
            
            if(accId == selfRegAccId){
                userRoleWap.selfAcc = true;
                userRoleWap.company = con.Company_Name__c;	
            }
            else{
                userRoleWap.selfAcc = false;
                userRoleWap.company = con.Account.Name;
            } 
            
            
            //This method is used to get the contact count to show/hide deactivate button in update profile page
            List<Contact> conCount = [Select toLabel(Portal_User_Roles__c) from Contact where AccountId = :accId and status__c =: true];
            Integer count = 0;
            if(conCount.size()> 1){
                for(Contact c:conCount){
                    system.debug('c'+c);
                    if(c.Portal_User_Roles__c != 'Customer'){
                        count++;
                    }
                }    
            }            
            userRoleWap.roleCount = count;
            
        }catch(Exception e){
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('ManageColleagues page','Community Component Error',e.getStackTraceString(),
                                'Class:YG_LoggedUserRoleController; Method: getNotifyUserRole(); Line #:'+e.getLineNumber()+'; Message:'+e.getMessage(),
                                UserInfo.getUserId());
        }
        
   return userRoleWap;
    }
    
     public class NoftifyUserRoleWapper{
         @AuraEnabled public String fName;
         @AuraEnabled public String lName;
         @AuraEnabled public String email;
         @AuraEnabled public String phone;
         @AuraEnabled public String company;
         @AuraEnabled public String role;
         @AuraEnabled public Integer roleCount;
         @AuraEnabled public Boolean selfAcc;
    }
    
}