force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is used to store the Status</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>This object define the relationship between the Contact and Asset object.</description>
    <label>Customer Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the contact object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Asset</relationshipLabel>
    <relationshipName>Customer_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/Customer_Plant__c.object-meta.xml
<CustomObject>
    <description>This is a Junction object for Contact and Plant</description>
    <label>Customer Plant</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Customer Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Plant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for contact lookup on Customer Plant Object.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Plant</relationshipLabel>
    <relationshipName>Customer_Plant</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is used for plant lookup on Customer Plant Object.</description>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Customer Plant</relationshipLabel>
    <relationshipName>Customer_Plant</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request site access</fullName>
                <default>true</default>
                <label>Request site access</label>
            </value>
            <value>
                <fullName>Approved site access</fullName>
            </value>
            <value>
                <fullName>Decline site access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the plant details</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used for account lookup on plant.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant</relationshipLabel>
    <relationshipName>Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>This field is used to store the plant code.</description>
    <label>Plant Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <description>This field is use to store the plant name from API callout</description>
    <label>Plant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/YG_Community_Configuration__c/YG_Community_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object is used to store the custom setting for community portal.</description>
    <label>YG Community Configuration</label>
</CustomObject>

force-app/main/default/classes/YG_CommonController.cls
/*
*******************************************************************************************************
* (C) Copyright 2020 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Chitrakishore
* @version 1.0
* @created 15/06/2020
* @description 
* This class is used to write the methods for common functionality for all the modules.
*
* @test class name - YG_CommonControllerTest
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  12/04/2020			Jayaprasath				Added getMenuInfo()
*  04/19/2021			Kavya					Removed Customer_Plant__c Object and replaced with AccountContactRelation Object
*
*/

public class YG_CommonController {
    
    public static User userInformation =  YG_Utility.getLoggedInUserInfo(UserInfo.getUserId());
    
    @AuraEnabled
    public static CommonWrapper getPlantInfo(String langCode){
        
        Id cusPltId;
        
        List<DataWrapper> wrapperList = new List<DataWrapper>();
        
        CommonWrapper commonWrapper = new CommonWrapper();
       // try{
            if(null == langCode){
               langCode = 'EN';
            }
            
            system.debug('userInformation.ContactId :::'+userInformation.ContactId);
            // Retrieve logged in user's plants info
            /*List<Customer_Plant__c> cusPlantList = YG_HelperClass.getCusPlantInfo(userInformation.ContactId,langCode);*/
        List<AccountContactRelation> cusPlantList = YG_HelperClass.getCusPlantInfo(userInformation.ContactId,langCode);
            
            system.debug('cusPlantList::'+cusPlantList);
            
            /*for(Customer_Plant__c cusPlant: cusPlantList){
                DataWrapper wrapper = new DataWrapper();
                wrapper.plantCode = cusPlant.Plant__r.Plant_Code__c;
                wrapper.plantName = cusPlant.Plant__r.Plant_Name__c;                
                wrapperList.add(wrapper);
                
            }*/
        for(AccountContactRelation cusPlant: cusPlantList){
                DataWrapper wrapper = new DataWrapper();
                wrapper.plantCode = cusPlant.Account.AccountNumber;
                wrapper.plantName = cusPlant.Account.Name;                
                wrapperList.add(wrapper);
                
            }
            system.debug('wrapperList :::'+ wrapperList);
			commonWrapper.wrapper = wrapperList;    
            system.debug('commonWrapper :::'+ commonWrapper);
            
       /* }catch(Exception e){
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('Plant Page','Community Component Error',e.getStackTraceString(),
                               'Class:YG_CommonController; Method: getPlantInfo(); Line #:'+e.getLineNumber()+'; Message:'+e.getMessage(),
                               UserInfo.getUserId());
        }*/
        
        return commonWrapper;
    }
    
    public class CommonWrapper{
        @AuraEnabled public List<DataWrapper> wrapper; 
    }
    
    public class DataWrapper{
        @AuraEnabled public string plantCode; 
        @AuraEnabled public string plantName;
    }
    
    //This method is used to check the user's account has assigned plant or not
    @AuraEnabled 
    public static String checkContractOrIndividualCustomer(){
        Id accId = userInformation.Contact.AccountId;
        Id conId = userInformation.Contact.Id;
        String result;
        system.debug('userInformation.accId :::'+accId);
        system.debug('userInformation.conId :::'+conId);
        //Query to get the account number
        Account acc=[Select Id, AccountNumber From Account Where Id=: accId];
        System.debug('acc.AccountNumber'+acc.AccountNumber);
        if(acc.AccountNumber == null){
            result = 'Request Product';
        }else{
            result = 'Request Plant';
        }
        return result;
    }
    
    //This method is used to check the user's has product
    @AuraEnabled 
    public static MenuWrapper getMenuInfo(){
        Id conId = userInformation.Contact.Id;
        Id accId = userInformation.Contact.AccountId;
        String result;
        MenuWrapper menu = new MenuWrapper();
        try{
            
            List<Customer_Asset__c> custAsst = [Select Id from Customer_Asset__c where Contact__c =: conId ];
        	/*List<Customer_Plant__c> custPlnt = [Select Id,Contact__r.Account.AccountNumber,status__c from Customer_Plant__c where Contact__c = : conId ];*/
            List<AccountContactRelation> custPlnt = [Select Id,Contact.Account.AccountNumber,status__c from AccountContactRelation where ContactId = : conId ];
            Map<String, YG_Community_Configuration__c> allValues = new Map<String, YG_Community_Configuration__c>();        
        	allValues = YG_Community_Configuration__c.getAll();
            Id selfRegAccId = allValues.get('YGSelfRegisterAccountId').Text_1__c;
            set<string> myset = new set<string>(); 
            
            //to identify Self Reg User
            if(accId == selfRegAccId){
                
                if(custAsst.size() != 0){
                    menu.notify = 0; 
                }
                else{
                    menu.notify = 1;
                }
                menu.systemCount =  1; 
				menu.selfRegUser = true; 
                menu.productCount =  custAsst.size(); 
            }
            else{
              /*  For(Customer_Plant__c cp :custPlnt){ 
                    myset.add(cp.status__c); 
                }*/
                 For(AccountContactRelation cp :custPlnt){ 
                    myset.add(cp.status__c); 
                }
                if(myset.contains('Approved site access'))
                {
                    menu.systemCount =  custPlnt.size(); 
                }else{
                    menu.systemCount =  0; 
                }
                 
                menu.productCount =  custAsst.size(); 
                menu.selfRegUser = false;                
                if(custPlnt.size() == 0 && custAsst.size() == 0){
                    menu.notify = 2; 
                }
            }
            system.debug('menu'+menu);
            
        }
        catch(Exception e){
            system.debug('Exception Cause::'+e.getCause());
            system.debug('Exception LineNumber::'+e.getLineNumber());
            system.debug('Exception Message::'+e.getMessage());
            system.debug('Exception StackTrace::'+e.getStackTraceString());
            system.debug('Exception TypeName::'+e.getTypeName());
            YG_Utility.logError('Menu page','Menu Info Error',e.getStackTraceString(),
                                'Class:YG_CommonController; Method: getMenuInfo(); Line #:'+e.getLineNumber()+'; Message:'+e.getMessage(),
                                UserInfo.getUserId());
        }
        
        
        return menu;
    }
	public class MenuWrapper{
         @AuraEnabled public Integer productCount = 0;
         @AuraEnabled public Integer systemCount = 0;
         @AuraEnabled public Integer notify = 1;
         @AuraEnabled public Boolean selfRegUser;
    }
}