force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Category_of_Interest__c</fullName>
    <label>Category of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oscilloscopes</fullName>
            </value>
            <value>
                <fullName>Acquisition de Données</fullName>
            </value>
            <value>
                <fullName>Analyseurs de Puissance Numériques</fullName>
            </value>
            <value>
                <fullName>Générateurs/Sources/Calibrateurs/Manomètres</fullName>
            </value>
            <value>
                <fullName>Instruments de Mesure Optique</fullName>
            </value>
            <value>
                <fullName>Instruments de Test Portables</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
            <value>
                <fullName>Data Acquisition</fullName>
            </value>
            <value>
                <fullName>Digital Power Analyzers</fullName>
            </value>
            <value>
                <fullName>Generators/Sources/Calibrators/Manometers</fullName>
            </value>
            <value>
                <fullName>Optical Measuring Instruments</fullName>
            </value>
            <value>
                <fullName>Portable Test Instruments</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Optical field testers</fullName>
                <isActive>false</isActive>
                <label>Optical field testers</label>
            </value>
            <value>
                <fullName>Optical spectrum analyzers</fullName>
                <isActive>false</isActive>
                <label>Optical spectrum analyzers</label>
            </value>
            <value>
                <fullName>Optical test equipment</fullName>
                <isActive>false</isActive>
                <label>Optical test equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Tele_Qualified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tele_Qualified_Reason__c</fullName>
    <label>Tele-Qualified Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Material SBU</fullName>
    </customValue>
    <customValue>
        <fullName>Life SBU</fullName>
    </customValue>
    <customValue>
        <fullName>Products HQ</fullName>
    </customValue>
    <customValue> 
        <fullName>Digital Solutions HQ</fullName>
    </customValue>
    <customValue>
        <fullName>YMI SBU</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospace &amp; New Business SBU</fullName>
    </customValue>
    <description>Business Units for Yokogawa</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/YODA_RunAssignmentRules_Test.cls
/*
*******************************************************************************************************
* (C) Copyright 2021 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Hemalatha Gorthy
* @version 1.0
* @created 16/08/2021
* @description 
* This is a Run Assignment Rules Test class on Lead.
*
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  08/16/2021           Hemalatha Gorthy        Apex Test class to run assignment rules on Lead.
*/
@IsTest(SeeAllData = False)
public class YODA_RunAssignmentRules_Test {

    @testSetup 
    static void dataSetUp(){
            //Insert a test Lead
            Lead testLead1 = New Lead(Category_of_Interest__c = 'Oscilloscopes',
                                Company = 'TestLead',
                                FirstName = 'Test',
                                LastName = 'Assign',
                                Email = 'testLead@yokogawa.com',
                                Status = 'New',
                                Rating = 'Warm');
            
            Insert testLead1;
}
		
    @isTest
    public static void assignLeadsTest(){
        
        // Get the Lead that is inserted above
		List<id> idList = New List<id>();
        Lead myLead = [SELECT Id, firstname, lastname, OwnerId, Owner.Name, Rating, Country, Business_Unit__c  
                            FROM Lead WHERE Email = 'testLead@yokogawa.com' LIMIT 1];
        idList.add(myLead.id);
        
        //Test starts here
        Test.StartTest();        

        //Update status to 'Tele-Qualified'
        myLead.Status = 'Tele-Qualified';
        myLead.Tele_Qualified_Reason__c = 'Test Lead Assignment Rules';
        Update myLead;
        
		//Run assignment rules 
        YODA_RunAssignmentRules.reRunAssignmentRules(idList);
        
		// Owner is changed to 'Lead Queue'
		System.assertNotEquals(myLead.Owner.Name, Userinfo.getName(), 'Owner is changed to Lead Queue');
        
		Test.StopTest();

	}
}