force-app/main/default/objects/Applicable_Model__c/Applicable_Model__c.object-meta.xml
<CustomObject>
    <label>Applicable Model</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicable Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicable_Model__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Applicable Model</relationshipLabel>
    <relationshipName>Applicable_Model</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicable_Model__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Applicable Model</relationshipLabel>
    <relationshipName>Applicable_Model1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Applicable_Model__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If liked this field will replace the Applicable model text field</description>
    <inlineHelpText>If liked this field will replace the Applicable model text field</inlineHelpText>
    <label>Applicable Model</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Applicable Model</relationshipLabel>
    <relationshipName>ApplicableModel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field lookup the category table to define product category.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/YODA_AddProductstoKnowledgeCtlr.cls
public class YODA_AddProductstoKnowledgeCtlr{
    public string knowledgeId {get; set;}
    //public list<wrapperAppModel> listWrapper {get; set;}
    public map<string, wrapperAppModel> mapWrapper {get; set;}
    public string search {get; set;}
    public set<string> setAppModel;
    public list<Applicable_Model__c> listAppModel;
    
    public YODA_AddProductstoKnowledgeCtlr(){
        setAppModel = new set<string>();
        listAppModel = new list<Applicable_Model__c>();
        search = '';
        //listWrapper = new list<wrapperAppModel>();
        mapWrapper = new map<string, wrapperAppModel>();
        knowledgeId = ApexPages.CurrentPage().getparameters().get('id');
        for(Applicable_Model__c am : [select Product__c from Applicable_Model__c where Knowledge__c = :knowledgeId]){
            setAppModel.add(am.Product__c);
        }
        for(Product2 p : [Select Id, Name, ProductCode, Category__r.Name from Product2 where Id not in :setappModel Limit 1000]){
            //listWrapper.add(new wrapperAppModel(false, p));
            mapWrapper.put(p.Id, new wrapperAppModel(false, p));
        }
    }
    public class wrapperAppModel{
        public boolean isSelected {get; set;}
        public Product2  product{get; set;}
        public wrapperAppModel(boolean isSelected, Product2 product){
            this.isSelected = isSelected;
            this.product = product;
        }
    }
    
    public void search(){
        mapWrapper = new map<string, wrapperAppModel>();
        if(search == '' || search == null){
            for(Product2 p : [Select Id, Name, ProductCode, Category__r.Name from Product2 where Id not in :setappModel Limit 1000]){
            //listWrapper.add(new wrapperAppModel(false, p));
            mapWrapper.put(p.Id, new wrapperAppModel(false, p));
            }
        }
        else{
            string inpSearch = '%'+search+'%';
            for(Product2 p : [Select Id, Name, ProductCode, Category__r.Name from Product2 where Id not in :setappModel and (Name like :inpSearch or ProductCode like :inpSearch or Category__r.Name like :inpSearch) Limit 1000]){
            //listWrapper.add(new wrapperAppModel(false, p));
            mapWrapper.put(p.Id, new wrapperAppModel(false, p));
            }
        }
    }
    
    public pagereference Submit(){
        for(string wam : mapWrapper.keySet()){
            if(mapWrapper.get(wam).isSelected == true){
                Applicable_Model__c am = new Applicable_Model__c();
                am.Knowledge__c = knowledgeId;
                am.Product__c = mapWrapper.get(wam).product.Id;
                listAppModel.add(am);
            }
        }
        insert listAppModel;
        PageReference pageRef = new PageReference('/' + knowledgeId);
        aura.redirect(pageRef);
        return pageRef;
    }
    public pagereference Cancel(){   
        PageReference pageRef = new PageReference('/' + knowledgeId);
        aura.redirect(pageRef);
        return pageRef;
    }
     
}