force-app/main/default/objects/Applicable_Model__c/Applicable_Model__c.object-meta.xml
<CustomObject>
    <label>Applicable Model</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicable Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicable_Model__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Applicable Model</relationshipLabel>
    <relationshipName>Applicable_Model</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicable_Model__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Applicable Model</relationshipLabel>
    <relationshipName>Applicable_Model1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the product category.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field stores the lookup value with category hierarchy.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category</relationshipLabel>
    <relationshipName>Category</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Level__c.field-meta.xml
<CustomField>
    <fullName>Category_Level__c</fullName>
    <formula>TEXT(Category_Hierarchy__r.Category_Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <description>This field is used to store the product category type.</description>
    <label>Category Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/Category_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>This field is used to store the hierarchy of the product category.</description>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Category Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Category_Code__c</fullName>
    <description>This field is used to store the category code of the product.</description>
    <externalId>true</externalId>
    <label>Category Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Category_Hierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields lookup the same object&apos;s parent record.</description>
    <label>Category Hierarchy</label>
    <referenceTo>Category_Hierarchy__c</referenceTo>
    <relationshipLabel>Category Hierarchy</relationshipLabel>
    <relationshipName>CategoryHierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category_Hierarchy__c/fields/Category_Level__c.field-meta.xml
<CustomField>
    <fullName>Category_Level__c</fullName>
    <description>This field is used to store the category level of the product.</description>
    <label>Category Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Applicable_Model__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Model__c</fullName>
    <label>Applicable Model</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Knowledge</relationshipLabel>
    <relationshipName>Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Applicable_Model__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If liked this field will replace the Applicable model text field</description>
    <inlineHelpText>If liked this field will replace the Applicable model text field</inlineHelpText>
    <label>Applicable Model</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Applicable Model</relationshipLabel>
    <relationshipName>ApplicableModel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field lookup the category table to define product category.</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/YODA_AddProductstoKnowledgeCtlr_Test.cls
/*
*******************************************************************************************************
* (C) Copyright 2021 Yokogawa. All rights reserved.
* This code is property of Yokogawa. Use, duplication and
* disclosure in any form without permission of copyright holder is prohibited.
* 
******************************************************************************************************* 
* @author Kameron F
* @version 1.0
* @created 9/9/2021
* @description  
* This class is used for testing the YODA_AddProductstoKnowledgeCtlr controller connected to the 
* YODA_AddProductstoKnowledge VisualForce page
* @test class name - YODA_AddProductstoKnowledgeCtlr_Test
*  Change History:
*  MM/DD/YYYY			Developer Name			Comments
*  9/27/2021             Kameron F.              Created Class
*/
@isTest
public class YODA_AddProductstoKnowledgeCtlr_Test {
    @isTest
    static void main(){
        // Inserting all necessary objects to use the page
        Knowledge__kav KL = new Knowledge__kav(Title='Test', UrlName='TestUrl');
        insert KL;
        Category_Hierarchy__c CH = new Category_Hierarchy__c(Category_Code__c='0001',Category_Level__c=001,Name='TestCH');
        insert CH;
        Category__c CAT = new Category__c(Name='Test',Category_Type__c='TestType',Category_Hierarchy__c=CH.id);
        insert CAT;
        Product2 PR = new Product2(Name='TestProduct',Category__c=CAT.id);
        insert PR;
        Applicable_Model__c AM = new Applicable_Model__c(Knowledge__c = KL.id,Product__c=PR.id);
        insert AM;
        
       
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com'+RandomId);
        
        YODA_AddProductstoKnowledgeCtlr sc = new YODA_AddProductstoKnowledgeCtlr();
		//run as system user
        System.runAs(u) { 
            //PageReference pageRef = Page.YODA_AddProductstoKnowledge;
            PageReference pageRef = Page.YODA_AddProductstoKnowledge;
            pageRef.getParameters().put('knowledgeId',KL.iD);
            Test.setCurrentPage(pageRef);
            
            pageRef.getParameters().put('id', String.valueOf(KL.Id));
            sc.search = '';
            sc.search();
            System.assert(sc.mapWrapper.size()==1);
            
            PR = new Product2(Name='Test',Category__c=CAT.id);
            insert PR;
            
            sc.search='Test';
            sc.search();
            System.assert(sc.mapWrapper.size()==2);
            sc.mapWrapper.get(PR.id).isSelected = true;
        }
        sc.Submit();
        sc.Cancel();
    }
}